#!/usr/bin/perl
# Copyright (C) 2026 Huawei Technologies Co.,Ltd.
#
# dstore is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# dstore is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. if not, see <https://www.gnu.org/licenses/>.
# Generate wait events support files from wait_event_names.txt:
# - wait_state.h
# - wait_state.cpp
#
# src/common/instrument/wait_event/generate-wait_state_types.pl

use warnings;
use strict;
 
open my $wait_types, '<', $ARGV[0] or die;
 
my $htmp = "wait_state.h.tmp$$";
my $ctmp = "wait_state.cpp.tmp$$";
open my $h, '>', $htmp or die "Could not open $htmp: $!";
open my $c, '>', $ctmp or die "Could not open $ctmp: $!";
my $autogen =
  "/* autogenerated from src/common/instrument/wait_event/wait_state_names.txt, do not edit */\n";
print $h $autogen;
print $h "/* there is deliberately not an #ifndef WAIT_STATE_NAMES_H here */\n\n";
print $h "#include <stdint.h>\n";
print $c $autogen, "\n";
print $c "#include <stdint.h>\n";
print $c "namespace DSTORE {\n";
print $c "const char* GsStatWaitStateDesc[] = {\n";
print $c "    \"none\",\n";
print $h "/* ----------\n";
print $h " * dstore waiting states\n";
print $h " * ----------\n";
print $h " */\n";
print $h "namespace DSTORE {\n";
print $h "enum class GsStatWaitState {\n";
print $h "    STATE_WAIT_UNDEFINED,\n";
my $invalid_events = "";
while (<$wait_types>)
{
    chomp;
    # Skip comments
    next if /^#/;
    next if /^\s*$/;
    next if /^event_type/;
    die "unable to parse wait_state_names.txt"
      unless /^(\w+),\s*"(.*?)"$/;
    (my $wait_state_name, my $wait_state_desc) = ($1, $2);
    printf $c "    \"%s\", // %s\n", $wait_state_desc, $wait_state_name;
    printf $h "    %s, // %s\n",$wait_state_name,$wait_state_desc;
}

print $c "};\n";
print $c "\n";
print $c "const char* GetWaitStateName(uint32_t waitState)\n";
print $c "{\n";
print $c "    return GsStatWaitStateDesc[static_cast<uint32_t>(waitState)];\n";
print $c "}\n";
print $c "}\n";

print $h "    STATE_WAIT_NUM\n";
print $h "};\n";
print $h "const char* GetWaitStateName(uint32_t waitState);\n";
print $h "}\n";
close $h;
close $c;
 
rename($htmp, 'wait_state.h') || die "rename: $htmp: $!";
rename($ctmp, 'wait_state.cpp') || die "rename: $ctmp: $!";
 
close $wait_types;