#!/usr/bin/perl
# Copyright (C) 2026 Huawei Technologies Co.,Ltd.
#
# dstore is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# dstore is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. if not, see <https://www.gnu.org/licenses/>.
# Generate wait events support files from io_event_names.txt:
# - io_event.h
# - io_event.cpp
#
# src/common/instrument/wait_event/generate-io_event_types.pl

use warnings;
use strict;
 
open my $wait_types, '<', $ARGV[0] or die;
 
my $htmp = "io_event.h.tmp$$";
my $ctmp = "io_event.cpp.tmp$$";
open my $h, '>', $htmp or die "Could not open $htmp: $!";
open my $c, '>', $ctmp or die "Could not open $ctmp: $!";
my $autogen =
  "/* autogenerated from src/common/instrument/wait_event/io_event_names.txt, do not edit */\n";
print $h $autogen;
print $h "/* there is deliberately not an #ifndef IO_EVENT_NAMES_H here */\n\n";
print $h "#include <stdint.h>\n";
print $c $autogen, "\n";
print $c "#include <stdint.h>\n";
print $c "#include \"framework/dstore_stat_interface.h\"\n";
print $c "namespace DSTORE {\n";
print $c "const char* GsIOWaitEventDesc[] = {\n";
print $h "/* ----------\n";
print $h " * dstore io wait events\n";
print $h " * ----------\n";
print $h " */\n";
print $h "namespace DSTORE {\n";
print $h "enum class GsStatWaitEvent {\n";
print $h "    IO_EVENT_INVALID = 0x0A000000U - 1,\n";
while (<$wait_types>)
{
    chomp;
    # Skip comments
    next if /^#/;
    next if /^\s*$/;
    next if /^event_type/;
    die "unable to parse io_event_names.txt"
      unless /^(\w+),\s*"(.*?)"$/;
    (my $io_event_name, my $io_event_desc) = ($1, $2);
    printf $c "    \"%s\", // %s\n", $io_event_desc, $io_event_name;
    printf $h "    %s, // %s\n",$io_event_name,$io_event_desc;
}

print $c "};\n";
print $c "\n";
print $c "const char* GetIOEventName(uint32_t waitState)\n";
print $c "{\n";
print $c "    return GsIOWaitEventDesc[static_cast<uint32_t>(waitState - OPTUTIL_GSSTAT_WAIT_IO)];\n";
print $c "}\n";
print $c "}\n";

print $h "    IO_EVENT_END,\n";
print $h "    IO_EVENT_NUM = (int)IO_EVENT_END - (int)IO_EVENT_INVALID - 1\n";
print $h "};\n";
print $h "const char* GetIOEventName(uint32_t waitState);\n";
print $h "}\n";
close $h;
close $c;
 
rename($htmp, 'io_event.h') || die "rename: $htmp: $!";
rename($ctmp, 'io_event.cpp') || die "rename: $ctmp: $!";
 
close $wait_types;