/*
 * Copyright (C) 2026 Huawei Technologies Co.,Ltd.
 *
 * dstore is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * dstore is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. if not, see <https://www.gnu.org/licenses/>.
 */

#ifndef DSTORE_TABLESPACE_ERROR_CODE_H
#define DSTORE_TABLESPACE_ERROR_CODE_H

#include "common/dstore_common_utils.h"
#include "framework/dstore_modules.h"
#include "errorcode/dstore_error_struct.h"

namespace DSTORE {

enum TableSpaceErrorReason : uint32_t {
    SEGMENT_USE_AFTER_DROP = 0x1,
    DATA_SEGMENT_TYPE_INVALID = 0x2,
    SEGMENT_PARAMETER_INVALID = 0x3,
    TBS_PAGE_READ_FAILED = 0x4,
    SEGMENT_IS_NOT_INIT = 0x5,
    DATA_PAGE_INIT_CALLBACK_INVALID = 0x6,
    SEGMENT_EXTENT_COUNT_REACH_MAX = 0x7,
    TABLESPACE_ALLOC_EXTENT_FAILED = 0x8,
    TBS_PAGE_REQUEST_SIZE_INVALID = 0x9,
    FSM_TREE_LEVEL_REACH_MAX = 0xA,
    SEGMENT_HAS_NO_SPACE = 0xB,
    TBS_INIT_FAILED = 0xC,
    ALLOC_EXTENT_FAILED = 0xD,
    TBS_PAGEID_INVALID = 0xE,
    TBS_EXTENT_SIZE_INVALID = 0xF,
    FILE_SIZE_EXCEED_LIMIT = 0x10,
    FILE_BITMAP_GROUP_USE_UP = 0x11,
    FILE_SIZE_EXCEED_MAX_LIMIT = 0x12,
    FILE_COUNT_EXCEED_LIMIT = 0x13,
    TABLESPACE_USE_UP = 0x14,
    TBS_PARAMETER_INVALID = 0x15,
    TBS_FILE_EXIST = 0x16,
    TBS_SPACE_EXIST = 0x17,
    TBS_SPACE_NOT_EXIST = 0x18,
    TBS_SPACE_HAS_DROPPED = 0x19,
    TBS_FILE_NOT_OPEN = 0x1A,
    TBS_FILE_NOT_FOUND = 0x1B,
    TBS_ACQUIRE_LOCK_FAILED = 0x1C,
    TABLESPACE_DELETE_PART_FILES = 0x1D,
    TABLESPACE_DAMAGED = 0x1E,
    TABLESPACE_NOT_EXIST = 0x1F,
    FREESPACEMAP_ASSIGNMENT_FAILED = 0x20,
    PDB_FENCE_WRITE = 0x21,
    STORESPACE_IS_INVALID = 0x22,
    TBS_ERROR_MAX
};

const ErrorCode TBS_ERROR_SEGMENT_USE_AFTER_DROP =
    (ERROR_MODULE_TABLESPACE | ERROR_SEVERITY_ERROR | SEGMENT_USE_AFTER_DROP);
const ErrorCode TBS_ERROR_DATA_SEGMENT_TYPE_INVALID =
    (ERROR_MODULE_TABLESPACE | ERROR_SEVERITY_ERROR | DATA_SEGMENT_TYPE_INVALID);
const ErrorCode TBS_ERROR_SEGMENT_PARAMETER_INVALID =
    (ERROR_MODULE_TABLESPACE | ERROR_SEVERITY_ERROR | SEGMENT_PARAMETER_INVALID);
const ErrorCode TBS_ERROR_PAGE_READ_FAILED =
    (ERROR_MODULE_TABLESPACE | ERROR_SEVERITY_ERROR | TBS_PAGE_READ_FAILED);
const ErrorCode TBS_ERROR_SEGMENT_IS_NOT_INIT =
    (ERROR_MODULE_TABLESPACE | ERROR_SEVERITY_ERROR | SEGMENT_IS_NOT_INIT);
const ErrorCode TBS_ERROR_DATA_PAGE_INIT_CALLBACK_INVALID =
    (ERROR_MODULE_TABLESPACE | ERROR_SEVERITY_ERROR | DATA_PAGE_INIT_CALLBACK_INVALID);
const ErrorCode TBS_ERROR_SEGMENT_EXTENT_COUNT_REACH_MAX =
    (ERROR_MODULE_TABLESPACE | ERROR_SEVERITY_ERROR | SEGMENT_EXTENT_COUNT_REACH_MAX);
const ErrorCode TBS_ERROR_TABLESPACE_ALLOC_EXTENT_FAILED =
    (ERROR_MODULE_TABLESPACE | ERROR_SEVERITY_ERROR | TABLESPACE_ALLOC_EXTENT_FAILED);
const ErrorCode TBS_ERROR_PAGE_REQUEST_SIZE_INVALID =
    (ERROR_MODULE_TABLESPACE | ERROR_SEVERITY_ERROR | TBS_PAGE_REQUEST_SIZE_INVALID);
const ErrorCode TBS_ERROR_FSM_TREE_LEVEL_REACH_MAX =
    (ERROR_MODULE_TABLESPACE | ERROR_SEVERITY_ERROR | FSM_TREE_LEVEL_REACH_MAX);
const ErrorCode TBS_ERROR_SEGMENT_HAS_NO_SPACE =
    (ERROR_MODULE_TABLESPACE | ERROR_SEVERITY_ERROR | SEGMENT_HAS_NO_SPACE);
const ErrorCode TBS_ERROR_INIT_FAILED =
    (ERROR_MODULE_TABLESPACE | ERROR_SEVERITY_ERROR | TBS_INIT_FAILED);
const ErrorCode TBS_ERROR_ALLOC_EXTENT_FAILED =
    (ERROR_MODULE_TABLESPACE | ERROR_SEVERITY_ERROR | ALLOC_EXTENT_FAILED);
const ErrorCode TBS_ERROR_PAGEID_INVALID =
    (ERROR_MODULE_TABLESPACE | ERROR_SEVERITY_ERROR | TBS_PAGEID_INVALID);
const ErrorCode TBS_ERROR_EXTENT_SIZE_INVALID =
    (ERROR_MODULE_TABLESPACE | ERROR_SEVERITY_ERROR | TBS_EXTENT_SIZE_INVALID);
const ErrorCode TBS_ERROR_FILE_SIZE_EXCEED_LIMIT =
    (ERROR_MODULE_TABLESPACE | ERROR_SEVERITY_ERROR | FILE_SIZE_EXCEED_LIMIT);
const ErrorCode TBS_ERROR_FILE_BITMAP_GROUP_USE_UP =
    (ERROR_MODULE_TABLESPACE | ERROR_SEVERITY_ERROR | FILE_BITMAP_GROUP_USE_UP);
const ErrorCode TBS_ERROR_FILE_SIZE_EXCEED_MAX_LIMIT =
    (ERROR_MODULE_TABLESPACE | ERROR_SEVERITY_ERROR | FILE_SIZE_EXCEED_MAX_LIMIT);
const ErrorCode TBS_ERROR_FILE_COUNT_EXCEED_LIMIT =
    (ERROR_MODULE_TABLESPACE | ERROR_SEVERITY_ERROR | FILE_COUNT_EXCEED_LIMIT);
const ErrorCode TBS_ERROR_TABLESPACE_USE_UP =
    (ERROR_MODULE_TABLESPACE | ERROR_SEVERITY_ERROR | TABLESPACE_USE_UP);
const ErrorCode TBS_ERROR_PARAMETER_INVALID =
    (ERROR_MODULE_TABLESPACE | ERROR_SEVERITY_ERROR | TBS_PARAMETER_INVALID);
const ErrorCode TBS_ERROR_FILE_EXIST =
    (ERROR_MODULE_TABLESPACE | ERROR_SEVERITY_ERROR | TBS_FILE_EXIST);
const ErrorCode TBS_ERROR_SPACE_EXIST =
    (ERROR_MODULE_TABLESPACE | ERROR_SEVERITY_ERROR | TBS_SPACE_EXIST);
const ErrorCode TBS_ERROR_SPACE_NOT_EXIST =
    (ERROR_MODULE_TABLESPACE | ERROR_SEVERITY_ERROR | TBS_SPACE_NOT_EXIST);
const ErrorCode TBS_ERROR_SPACE_HAS_DROPPED =
    (ERROR_MODULE_TABLESPACE | ERROR_SEVERITY_ERROR | TBS_SPACE_HAS_DROPPED);
const ErrorCode TBS_ERROR_FILE_NOT_OPEN =
    (ERROR_MODULE_TABLESPACE | ERROR_SEVERITY_ERROR | TBS_FILE_NOT_OPEN);
const ErrorCode TBS_ERROR_FILE_NOT_FOUND =
    (ERROR_MODULE_TABLESPACE | ERROR_SEVERITY_ERROR | TBS_FILE_NOT_FOUND);
const ErrorCode TBS_ERROR_ACQUIRE_LOCK_FAILED =
    (ERROR_MODULE_TABLESPACE | ERROR_SEVERITY_ERROR | TBS_ACQUIRE_LOCK_FAILED);
const ErrorCode TBS_ERROR_TABLESPACE_DELETE_PART_FILES =
    (ERROR_MODULE_TABLESPACE | ERROR_SEVERITY_ERROR | TABLESPACE_DELETE_PART_FILES);
const ErrorCode TBS_ERROR_TABLESPACE_DAMAGED =
    (ERROR_MODULE_TABLESPACE | ERROR_SEVERITY_ERROR | TABLESPACE_DAMAGED);
const ErrorCode TBS_ERROR_TABLESPACE_NOT_EXIST =
    (ERROR_MODULE_TABLESPACE | ERROR_SEVERITY_ERROR | TABLESPACE_NOT_EXIST);
const ErrorCode TBS_ERROR_FREESPACEMAP_ASSIGNMENT_FAILED =
    (ERROR_MODULE_TABLESPACE | ERROR_SEVERITY_ERROR | FREESPACEMAP_ASSIGNMENT_FAILED);
const ErrorCode TBS_ERROR_PDB_FENCE_WRITE =
    (ERROR_MODULE_TABLESPACE | ERROR_SEVERITY_ERROR | PDB_FENCE_WRITE);
const ErrorCode TBS_ERROR_STORESPACE_IS_INVALID =
    (ERROR_MODULE_TABLESPACE | ERROR_SEVERITY_ERROR | STORESPACE_IS_INVALID);

} /* namespace DSTORE */

#endif
