/*
 * Copyright (C) 2026 Huawei Technologies Co.,Ltd.
 *
 * dstore is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * dstore is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. if not, see <https://www.gnu.org/licenses/>.
 */

#ifndef DSTORE_TRANSACTION_ERROR_CODE_H
#define DSTORE_TRANSACTION_ERROR_CODE_H

#include "common/dstore_common_utils.h"
#include "framework/dstore_modules.h"
#include "errorcode/dstore_error_struct.h"

namespace DSTORE {

enum TransactionErrorReason : uint32_t {
    NO_ACTIVE_TRANSACTION = 0x1,
    ACTIVE_SQL_TRANSACTION = 0x2,
    TRANSACTION_INVALID_TBLOCK_STATE = 0x3,
    TRANSACTION_INVALID_STATE = 0x4,
    TRANSACTION_INVALID_CSN = 0x5,
    TRANSACTION_INVALID_SAVEPOINT = 0x6,
    SAVEPOINT_NOT_FOUND = 0x7,
    TRANSACTION_SAME_THREAD_DEADLOCK = 0x8,
    TRANSACTION_OUT_OF_MEMORY = 0x9,
    DISABLE_SQL_TRANSACTION = 0xA,
    TRANSACTION_PDB_FENCE_WRITE = 0xB,
    TRANSACTION_RUNTIME_NOT_INITIALIZED = 0xC,
    TRANSACTION_INVALID_PARAM = 0xD,
    CSN_OWNER_ONLY_CALL = 0xE,
    TRANSACTION_NODE_RPC_TIMEOUT = 0xF,
    FAILED_TO_GET_BLOCK_COUNT = 0x10,
    FAILED_TO_EXTEND_BLOCK = 0x11,
    TRANSACTION_FILE_ACCESS = 0x12,
    TRANSACTION_INCOMPLETE_RPC_MESSAGE = 0x13,
    TRANSACTION_RPC_SEND_RECEIVE = 0x14,
    TRANSACTION_NODE_RPC_ERROR = 0x15,
    GLOBAL_CLOCK_NOT_SYNCED = 0x16,
    GCLOCK_OVER_WAIT_TIME = 0x17,
    GCLOCK_BIGGER_ERROR_BOUND = 0x18,
    TRANSACTION_EXCEED_MAX_ERRBOUND = 0x19,
    GCLOCK_CANNOT_SYNC_WITH_CSN_OWNER = 0x1A,
    FAILED_TO_GET_CSN = 0x1B,
    TRANSACTION_WAIT_TIMEOUT = 0x1C,
    TRANSACTION_REMOTE_FAILED = 0x1D,
    TRANSACTION_ERROR_MAX
};

const ErrorCode TRANSACTION_WARNING_NO_ACTIVE_TRANSACTION =
    (ERROR_MODULE_TRANSACTION | ERROR_SEVERITY_WARNING | NO_ACTIVE_TRANSACTION);
const ErrorCode TRANSACTION_WARNING_ACTIVE_SQL_TRANSACTION =
    (ERROR_MODULE_TRANSACTION | ERROR_SEVERITY_WARNING | ACTIVE_SQL_TRANSACTION);
const ErrorCode TRANSACTION_ERROR_INVALID_TBLOCK_STATE =
    (ERROR_MODULE_TRANSACTION | ERROR_SEVERITY_ERROR | TRANSACTION_INVALID_TBLOCK_STATE);
const ErrorCode TRANSACTION_ERROR_INVALID_STATE =
    (ERROR_MODULE_TRANSACTION | ERROR_SEVERITY_ERROR | TRANSACTION_INVALID_STATE);
const ErrorCode TRANSACTION_ERROR_INVALID_CSN =
    (ERROR_MODULE_TRANSACTION | ERROR_SEVERITY_ERROR | TRANSACTION_INVALID_CSN);
const ErrorCode TRANSACTION_ERROR_INVALID_SAVEPOINT =
    (ERROR_MODULE_TRANSACTION | ERROR_SEVERITY_ERROR | TRANSACTION_INVALID_SAVEPOINT);
const ErrorCode TRANSACTION_ERROR_SAVEPOINT_NOT_FOUND =
    (ERROR_MODULE_TRANSACTION | ERROR_SEVERITY_ERROR | SAVEPOINT_NOT_FOUND);
const ErrorCode TRANSACTION_INFO_SAME_THREAD_DEADLOCK =
    (ERROR_MODULE_TRANSACTION | ERROR_SEVERITY_INFO | TRANSACTION_SAME_THREAD_DEADLOCK);
const ErrorCode TRANSACTION_ERROR_OUT_OF_MEMORY =
    (ERROR_MODULE_TRANSACTION | ERROR_SEVERITY_ERROR | TRANSACTION_OUT_OF_MEMORY);
const ErrorCode TRANSACTION_ERROR_DISABLE_SQL_TRANSACTION =
    (ERROR_MODULE_TRANSACTION | ERROR_SEVERITY_ERROR | DISABLE_SQL_TRANSACTION);
const ErrorCode TRANSACTION_ERROR_PDB_FENCE_WRITE =
    (ERROR_MODULE_TRANSACTION | ERROR_SEVERITY_ERROR | TRANSACTION_PDB_FENCE_WRITE);
const ErrorCode TRANSACTION_ERROR_RUNTIME_NOT_INITIALIZED =
    (ERROR_MODULE_TRANSACTION | ERROR_SEVERITY_ERROR | TRANSACTION_RUNTIME_NOT_INITIALIZED);
const ErrorCode TRANSACTION_ERROR_INVALID_PARAM =
    (ERROR_MODULE_TRANSACTION | ERROR_SEVERITY_ERROR | TRANSACTION_INVALID_PARAM);
const ErrorCode TRANSACTION_ERROR_CSN_OWNER_ONLY_CALL =
    (ERROR_MODULE_TRANSACTION | ERROR_SEVERITY_ERROR | CSN_OWNER_ONLY_CALL);
const ErrorCode TRANSACTION_ERROR_NODE_RPC_TIMEOUT =
    (ERROR_MODULE_TRANSACTION | ERROR_SEVERITY_ERROR | TRANSACTION_NODE_RPC_TIMEOUT);
const ErrorCode TRANSACTION_ERROR_FAILED_TO_GET_BLOCK_COUNT =
    (ERROR_MODULE_TRANSACTION | ERROR_SEVERITY_ERROR | FAILED_TO_GET_BLOCK_COUNT);
const ErrorCode TRANSACTION_ERROR_FAILED_TO_EXTEND_BLOCK =
    (ERROR_MODULE_TRANSACTION | ERROR_SEVERITY_ERROR | FAILED_TO_EXTEND_BLOCK);
const ErrorCode TRANSACTION_ERROR_FILE_ACCESS =
    (ERROR_MODULE_TRANSACTION | ERROR_SEVERITY_ERROR | TRANSACTION_FILE_ACCESS);
const ErrorCode TRANSACTION_ERROR_INCOMPLETE_RPC_MESSAGE =
    (ERROR_MODULE_TRANSACTION | ERROR_SEVERITY_ERROR | TRANSACTION_INCOMPLETE_RPC_MESSAGE);
const ErrorCode TRANSACTION_ERROR_RPC_SEND_RECEIVE =
    (ERROR_MODULE_TRANSACTION | ERROR_SEVERITY_ERROR | TRANSACTION_RPC_SEND_RECEIVE);
const ErrorCode TRANSACTION_ERROR_NODE_RPC_ERROR =
    (ERROR_MODULE_TRANSACTION | ERROR_SEVERITY_ERROR | TRANSACTION_NODE_RPC_ERROR);
const ErrorCode TRANSACTION_ERROR_GLOBAL_CLOCK_NOT_SYNCED =
    (ERROR_MODULE_TRANSACTION | ERROR_SEVERITY_ERROR | GLOBAL_CLOCK_NOT_SYNCED);
const ErrorCode TRANSACTION_WARNING_GCLOCK_OVER_WAIT_TIME =
    (ERROR_MODULE_TRANSACTION | ERROR_SEVERITY_WARNING | GCLOCK_OVER_WAIT_TIME);
const ErrorCode TRANSACTION_WARNING_GCLOCK_BIGGER_ERROR_BOUND =
    (ERROR_MODULE_TRANSACTION | ERROR_SEVERITY_WARNING | GCLOCK_BIGGER_ERROR_BOUND);
const ErrorCode TRANSACTION_WARNING_EXCEED_MAX_ERRBOUND =
    (ERROR_MODULE_TRANSACTION | ERROR_SEVERITY_WARNING | TRANSACTION_EXCEED_MAX_ERRBOUND);
const ErrorCode TRANSACTION_WARNING_GCLOCK_CANNOT_SYNC_WITH_CSN_OWNER =
    (ERROR_MODULE_TRANSACTION | ERROR_SEVERITY_WARNING | GCLOCK_CANNOT_SYNC_WITH_CSN_OWNER);
const ErrorCode TRANSACTION_ERROR_FAILED_TO_GET_CSN =
    (ERROR_MODULE_TRANSACTION | ERROR_SEVERITY_ERROR | FAILED_TO_GET_CSN);
const ErrorCode TRANSACTION_ERROR_WAIT_TIMEOUT =
    (ERROR_MODULE_TRANSACTION | ERROR_SEVERITY_ERROR | TRANSACTION_WAIT_TIMEOUT);
const ErrorCode TRANSACTION_ERROR_REMOTE_FAILED =
    (ERROR_MODULE_TRANSACTION | ERROR_SEVERITY_ERROR | TRANSACTION_REMOTE_FAILED);

} /* namespace DSTORE */

#endif
