/*
 * Copyright (C) 2026 Huawei Technologies Co.,Ltd.
 *
 * dstore is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * dstore is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. if not, see <https://www.gnu.org/licenses/>.
 */

#ifndef DSTORE_FRAMEWORK_ERROR_CODE_H
#define DSTORE_FRAMEWORK_ERROR_CODE_H

#include "common/dstore_common_utils.h"
#include "framework/dstore_modules.h"
#include "errorcode/dstore_error_struct.h"

namespace DSTORE {

enum FrameworkErrorReason : uint32_t {
    FAILED_TO_CREATE_STORE_SPACE = 0x1,
    FAILED_TO_GET_LIBRARY = 0x2,
    FILE_ALREADY_CREATED_OR_OPEN = 0x3,
    FAILED_TO_RENAME = 0x4,
    FAILED_TO_CREATE_FILE = 0x5,
    FILE_NOT_CLOSED = 0x6,
    FAILED_TO_REMOVE_FILE = 0x7,
    FILE_ALREADY_EXISTS = 0x8,
    FILE_NOT_EXISTS = 0x9,
    FAILED_TO_OPEN_FILE = 0xA,
    FAILED_TO_CLOSE_FILE = 0xB,
    FILE_NOT_OPENED = 0xC,
    FAILED_TO_PREAD_FILE = 0xD,
    FSYNC_FILE_NOT_OPENED = 0xE,
    FAILED_TO_FSYNC = 0xF,
    FAILED_TO_GET_SIZE = 0x10,
    FAILED_TO_EXTEND = 0x11,
    FAILED_TO_TRUNCATE = 0x12,
    FAILED_TO_IO_FENCING = 0x13,
    DUPLICATE_ADD_ACTIVE = 0x14,
    VFS_NO_AVAILABLE_SLOT = 0x15,
    NULL_CLUSTER_NAME = 0x16,
    FILE_DESCRIPTOR_EMPTY = 0x17,
    HASH_ENTRY_INSERT_FAILED = 0x18,
    HASH_ENTRY_FIND_FAILED = 0x19,
    HASH_ENTRY_REMOVE_FAILED = 0x1A,
    FAILED_TO_INIT_VFS_MODULE = 0x1B,
    FAILED_TO_CREATE_VFS = 0x1C,
    FAILED_TO_OPEN_VFS = 0x1D,
    FAILED_TO_MOUNT_VFS = 0x1E,
    FAILED_TO_CREATE_SNAPSHOT = 0x1F,
    FAILED_TO_OPEN_SNAPSHOT = 0x20,
    FAILED_TO_DROP_SNAPSHOT = 0x21,
    FAILED_TO_ROLLBACK_SNAPSHOT = 0x22,
    FAILED_TO_GET_FILENAME = 0x23,
    FRAMEWORK_INVALID_PARAMETER = 0x24,
    FAILED_TO_PREAD_ASYNC = 0x25,
    FAILED_TO_PWRITE_SYNC = 0x26,
    FAILED_TO_PWRITE_ASYNC = 0x27,
    FAILED_TO_GET_LOCK = 0x28,
    FRAMEWORK_OUT_OF_MEMORY = 0x29,
    FRAMEWORK_ERROR_MAX
};

const ErrorCode VFS_ERROR_FAILED_TO_CREATE_STORE_SPACE =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_ERROR | FAILED_TO_CREATE_STORE_SPACE);
const ErrorCode VFS_ERROR_FAILED_TO_GET_LIBRARY =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_ERROR | FAILED_TO_GET_LIBRARY);
const ErrorCode VFS_ERROR_FILE_ALREADY_CREATED_OR_OPEN =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_ERROR | FILE_ALREADY_CREATED_OR_OPEN);
const ErrorCode VFS_ERROR_FAILED_TO_RENAME =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_ERROR | FAILED_TO_RENAME);
const ErrorCode VFS_WARNING_FAILED_TO_CREATE_FILE =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_WARNING | FAILED_TO_CREATE_FILE);
const ErrorCode VFS_WARNING_FILE_NOT_CLOSED =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_WARNING | FILE_NOT_CLOSED);
const ErrorCode VFS_WARNING_FAILED_TO_REMOVE_FILE =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_WARNING | FAILED_TO_REMOVE_FILE);
const ErrorCode VFS_WARNING_FILE_ALREADY_EXISTS =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_WARNING | FILE_ALREADY_EXISTS);
const ErrorCode VFS_WARNING_FILE_NOT_EXISTS =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_WARNING | FILE_NOT_EXISTS);
const ErrorCode VFS_FATAL_FAILED_TO_OPEN_FILE =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_FATAL | FAILED_TO_OPEN_FILE);
const ErrorCode VFS_WARNING_FAILED_TO_CLOSE_FILE =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_WARNING | FAILED_TO_CLOSE_FILE);
const ErrorCode VFS_WARNING_FILE_NOT_OPENED =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_WARNING | FILE_NOT_OPENED);
const ErrorCode VFS_WARNING_FAILED_TO_PREAD_FILE =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_WARNING | FAILED_TO_PREAD_FILE);
const ErrorCode VFS_WARNING_FSYNC_FILE_NOT_OPENED =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_WARNING | FSYNC_FILE_NOT_OPENED);
const ErrorCode VFS_WARNING_FAILED_TO_FSYNC =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_WARNING | FAILED_TO_FSYNC);
const ErrorCode VFS_WARNING_FAILED_TO_GET_SIZE =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_WARNING | FAILED_TO_GET_SIZE);
const ErrorCode VFS_WARNING_FAILED_TO_EXTEND =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_WARNING | FAILED_TO_EXTEND);
const ErrorCode VFS_WARNING_FAILED_TO_TRUNCATE =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_WARNING | FAILED_TO_TRUNCATE);
const ErrorCode VFS_WARNING_FAILED_TO_IO_FENCING =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_WARNING | FAILED_TO_IO_FENCING);
const ErrorCode VFS_WARNING_DUPLICATE_ADD_ACTIVE =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_WARNING | DUPLICATE_ADD_ACTIVE);
const ErrorCode VFS_WARNING_NO_AVAILABLE_SLOT =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_WARNING | VFS_NO_AVAILABLE_SLOT);
const ErrorCode VFS_WARNING_NULL_CLUSTER_NAME =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_WARNING | NULL_CLUSTER_NAME);
const ErrorCode VFS_WARNING_FILE_DESCRIPTOR_EMPTY =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_WARNING | FILE_DESCRIPTOR_EMPTY);
const ErrorCode VFS_ERROR_HASH_ENTRY_INSERT_FAILED =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_ERROR | HASH_ENTRY_INSERT_FAILED);
const ErrorCode VFS_WARNING_HASH_ENTRY_FIND_FAILED =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_WARNING | HASH_ENTRY_FIND_FAILED);
const ErrorCode VFS_ERROR_HASH_ENTRY_REMOVE_FAILED =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_ERROR | HASH_ENTRY_REMOVE_FAILED);
const ErrorCode VFS_ERROR_FAILED_TO_INIT_VFS_MODULE =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_ERROR | FAILED_TO_INIT_VFS_MODULE);
const ErrorCode VFS_ERROR_FAILED_TO_CREATE_VFS =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_ERROR | FAILED_TO_CREATE_VFS);
const ErrorCode VFS_ERROR_FAILED_TO_OPEN_VFS =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_ERROR | FAILED_TO_OPEN_VFS);
const ErrorCode VFS_ERROR_FAILED_TO_MOUNT_VFS =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_ERROR | FAILED_TO_MOUNT_VFS);
const ErrorCode VFS_ERROR_FAILED_TO_CREATE_SNAPSHOT =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_ERROR | FAILED_TO_CREATE_SNAPSHOT);
const ErrorCode VFS_ERROR_FAILED_TO_OPEN_SNAPSHOT =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_ERROR | FAILED_TO_OPEN_SNAPSHOT);
const ErrorCode VFS_ERROR_FAILED_TO_DROP_SNAPSHOT =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_ERROR | FAILED_TO_DROP_SNAPSHOT);
const ErrorCode VFS_ERROR_FAILED_TO_ROLLBACK_SNAPSHOT =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_ERROR | FAILED_TO_ROLLBACK_SNAPSHOT);
const ErrorCode VFS_ERROR_FAILED_TO_GET_FILENAME =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_ERROR | FAILED_TO_GET_FILENAME);
const ErrorCode VFS_ERROR_INVALID_PARAMETER =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_ERROR | FRAMEWORK_INVALID_PARAMETER);
const ErrorCode VFS_ERROR_FAILED_TO_PREAD_ASYNC =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_ERROR | FAILED_TO_PREAD_ASYNC);
const ErrorCode VFS_ERROR_FAILED_TO_PWRITE_SYNC =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_ERROR | FAILED_TO_PWRITE_SYNC);
const ErrorCode VFS_ERROR_FAILED_TO_PWRITE_ASYNC =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_ERROR | FAILED_TO_PWRITE_ASYNC);
const ErrorCode VFS_ERROR_FAILED_TO_GET_LOCK =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_ERROR | FAILED_TO_GET_LOCK);
const ErrorCode FRAMEWORK_ERROR_OUT_OF_MEMORY =
    (ERROR_MODULE_FRAMEWORK | ERROR_SEVERITY_ERROR | FRAMEWORK_OUT_OF_MEMORY);

} /* namespace DSTORE */

#endif
