/*
 * Copyright (C) 2026 Huawei Technologies Co.,Ltd.
 *
 * dstore is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * dstore is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. if not, see <https://www.gnu.org/licenses/>.
 */

#ifndef DSTORE_INDEX_ERROR_CODE_H
#define DSTORE_INDEX_ERROR_CODE_H

#include "common/dstore_common_utils.h"
#include "framework/dstore_modules.h"
#include "errorcode/dstore_error_struct.h"

namespace DSTORE {

enum IndexErrorReason : uint32_t {
    FAIL_CREATE_BTREE_SMGR = 0x1,
    UNKOWN_META_PAGE = 0x2,
    UNSUPPORTTED_DATA_TYPE = 0x3,
    NO_LIVE_ROOT_FOUND = 0x4,
    ROOT_PAGE_LEVEL_MISMATCH = 0x5,
    FAIL_CREATE_NEW_PAGE = 0x6,
    FAIL_BUILD_INDEX_FOR_PAGE_DAMAGED = 0x7,
    FAIL_BUILD_INDEX_FOR_MISSING_ROOT = 0x8,
    OVERWRITE_HIGHKEY = 0x9,
    INSERT_UNIQUE_CHECK = 0xA,
    MOVE_END = 0xB,
    FAILED_TO_FIND_DELETING_TARGET = 0xC,
    NO_ROOT_PAGE = 0xD,
    ROOT_LEVEL_NOT_MATCHED = 0xE,
    ADD_ITEM_FAIL = 0xF,
    FAIL_SPLIT_FOR_NO_TD_SPACE = 0x10,
    FAIL_REFIND_PARENT_KEY = 0x11,
    FAIL_ADD_HIGH_KEY_TO_RIGHT = 0x12,
    FAIL_ADD_NEW_ITEM_TO_LEFT = 0x13,
    FAIL_ADD_NEW_ITEM_TO_RIGHT = 0x14,
    FAIL_ADD_ORIGIN_ITEM_TO_LEFT = 0x15,
    FAIL_ADD_ORIGIN_ITEM_TO_RIGHT = 0x16,
    RIGHT_LEFT_LINK_NOT_MATCH = 0x17,
    UNRECOGNIZED_ROWCOMPARETYPE = 0x18,
    COULD_NOT_FIND_LEFT_SIBLING = 0x19,
    INVALID_SCAN_DIRECTION = 0x1A,
    COULD_NOT_FIND_FEASIBLE_SPLIT_POINT = 0x1B,
    UNRECOGNIZED_STRATEGY_NUMBER = 0x1C,
    INDEX_KEYS_MUST_BE_ORDERED_BY_ATTRIBUTE = 0x1D,
    CHANGED_NO_PARENT_LEAF = 0x1E,
    FAIL_BUILD_GLOBAL_INDEX = 0x1F,
    FAIL_FOR_HUGE_INDEX_TUPLE = 0x20,
    FOR_INVLAID_LAST_HIKEY = 0x21,
    FAIL_DELETE_TUPLE_FOR_ALLOCATE_TDID = 0x22,
    FAIL_SEARCH_INSERT_FOR_PAGE_DAMAGED = 0x23,
    INDEX_INPUT_PARAM_WRONG = 0x24,
    INDEX_MEMORY_ALLOC = 0x25,
    UNMATCHED_CCINDEX_STATUS = 0x26,
    FAIL_FOR_INVALID_HEAP_CTID = 0x27,
    FAIL_FOR_INVALID_DML_TYPE = 0x28,
    FAIL_BUILD_CONCURRENTLY = 0x29,
    INVALID_WAITING_TYPE = 0x2A,
    DUPLICATE_TO_THE_SAME_RECORD = 0x2B,
    EXPRESSION_VALUE_ERR = 0x2C,
    UNEXPECTED_NULL_VALUE = 0x2D,
    BTREE_STRUCTURE_DAMAGED = 0x2E,
    INDEX_FAIL_READ_PAGE = 0x2F,
    PAGE_DIFF_IN_BUFTAG = 0x30,
    INDEX_PAGE_EMPTY = 0x31,
    PAGE_DIFF_IN_HEADER = 0x32,
    PAGE_IS_NOT_BTRPAGE = 0x33,
    PAGE_IS_NOT_INITIALIZED_AS_BTRPAGE = 0x34,
    INDEX_TUPLE_DAMAGED = 0x35,
    LOW_IS_GREATER_THAN_MAX_OFFSET = 0x36,
    FAILED_UPDATE_BTRMETA_ROOT = 0x37,
    FAILED_TO_BROADCAST_WAITING_MESSAGE = 0x38,
    FAILED_TO_GET_SORTED_TUPLE = 0x39,
    UNCOMMITTED_TUPLE_FOUND_WHEN_BUILDING = 0x3A,
    INVALID_SNAPSHOT_FOR_INDEX_BUILDING = 0x3B,
    INDEX_ERROR_MAX
};

const ErrorCode INDEX_ERROR_FAIL_CREATE_BTREE_SMGR =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | FAIL_CREATE_BTREE_SMGR);
const ErrorCode INDEX_ERROR_UNKOWN_META_PAGE =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | UNKOWN_META_PAGE);
const ErrorCode INDEX_ERROR_UNSUPPORTTED_DATA_TYPE =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | UNSUPPORTTED_DATA_TYPE);
const ErrorCode INDEX_ERROR_NO_LIVE_ROOT_FOUND =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | NO_LIVE_ROOT_FOUND);
const ErrorCode INDEX_ERROR_ROOT_PAGE_LEVEL_MISMATCH =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | ROOT_PAGE_LEVEL_MISMATCH);
const ErrorCode INDEX_ERROR_FAIL_CREATE_NEW_PAGE =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | FAIL_CREATE_NEW_PAGE);
const ErrorCode INDEX_ERROR_FAIL_BUILD_INDEX_FOR_PAGE_DAMAGED =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | FAIL_BUILD_INDEX_FOR_PAGE_DAMAGED);
const ErrorCode INDEX_ERROR_FAIL_BUILD_INDEX_FOR_MISSING_ROOT =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | FAIL_BUILD_INDEX_FOR_MISSING_ROOT);
const ErrorCode INDEX_ERROR_OVERWRITE_HIGHKEY =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | OVERWRITE_HIGHKEY);
const ErrorCode INDEX_ERROR_INSERT_UNIQUE_CHECK =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | INSERT_UNIQUE_CHECK);
const ErrorCode INDEX_ERROR_MOVE_END =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | MOVE_END);
const ErrorCode INDEX_ERROR_FAILED_TO_FIND_DELETING_TARGET =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | FAILED_TO_FIND_DELETING_TARGET);
const ErrorCode INDEX_ERROR_NO_ROOT_PAGE =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | NO_ROOT_PAGE);
const ErrorCode INDEX_ERROR_ROOT_LEVEL_NOT_MATCHED =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | ROOT_LEVEL_NOT_MATCHED);
const ErrorCode INDEX_ERROR_ADD_ITEM_FAIL =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | ADD_ITEM_FAIL);
const ErrorCode INDEX_ERROR_FAIL_SPLIT_FOR_NO_TD_SPACE =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | FAIL_SPLIT_FOR_NO_TD_SPACE);
const ErrorCode INDEX_ERROR_FAIL_REFIND_PARENT_KEY =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | FAIL_REFIND_PARENT_KEY);
const ErrorCode INDEX_ERROR_FAIL_ADD_HIGH_KEY_TO_RIGHT =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | FAIL_ADD_HIGH_KEY_TO_RIGHT);
const ErrorCode INDEX_ERROR_FAIL_ADD_NEW_ITEM_TO_LEFT =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | FAIL_ADD_NEW_ITEM_TO_LEFT);
const ErrorCode INDEX_ERROR_FAIL_ADD_NEW_ITEM_TO_RIGHT =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | FAIL_ADD_NEW_ITEM_TO_RIGHT);
const ErrorCode INDEX_ERROR_FAIL_ADD_ORIGIN_ITEM_TO_LEFT =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | FAIL_ADD_ORIGIN_ITEM_TO_LEFT);
const ErrorCode INDEX_ERROR_FAIL_ADD_ORIGIN_ITEM_TO_RIGHT =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | FAIL_ADD_ORIGIN_ITEM_TO_RIGHT);
const ErrorCode INDEX_ERROR_RIGHT_LEFT_LINK_NOT_MATCH =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | RIGHT_LEFT_LINK_NOT_MATCH);
const ErrorCode INDEX_ERROR_UNRECOGNIZED_ROWCOMPARETYPE =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | UNRECOGNIZED_ROWCOMPARETYPE);
const ErrorCode INDEX_ERROR_COULD_NOT_FIND_LEFT_SIBLING =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | COULD_NOT_FIND_LEFT_SIBLING);
const ErrorCode INDEX_ERROR_INVALID_SCAN_DIRECTION =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | INVALID_SCAN_DIRECTION);
const ErrorCode INDEX_ERROR_COULD_NOT_FIND_FEASIBLE_SPLIT_POINT =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | COULD_NOT_FIND_FEASIBLE_SPLIT_POINT);
const ErrorCode INDEX_ERROR_UNRECOGNIZED_STRATEGY_NUMBER =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | UNRECOGNIZED_STRATEGY_NUMBER);
const ErrorCode INDEX_ERROR_INDEX_KEYS_MUST_BE_ORDERED_BY_ATTRIBUTE =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | INDEX_KEYS_MUST_BE_ORDERED_BY_ATTRIBUTE);
const ErrorCode INDEX_ERROR_CHANGED_NO_PARENT_LEAF =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | CHANGED_NO_PARENT_LEAF);
const ErrorCode INDEX_ERROR_FAIL_BUILD_GLOBAL_INDEX =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | FAIL_BUILD_GLOBAL_INDEX);
const ErrorCode INDEX_ERROR_FAIL_FOR_HUGE_INDEX_TUPLE =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | FAIL_FOR_HUGE_INDEX_TUPLE);
const ErrorCode INDEX_ERROR_FOR_INVLAID_LAST_HIKEY =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | FOR_INVLAID_LAST_HIKEY);
const ErrorCode INDEX_ERROR_FAIL_DELETE_TUPLE_FOR_ALLOCATE_TDID =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | FAIL_DELETE_TUPLE_FOR_ALLOCATE_TDID);
const ErrorCode INDEX_ERROR_FAIL_SEARCH_INSERT_FOR_PAGE_DAMAGED =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | FAIL_SEARCH_INSERT_FOR_PAGE_DAMAGED);
const ErrorCode INDEX_ERROR_INPUT_PARAM_WRONG =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | INDEX_INPUT_PARAM_WRONG);
const ErrorCode INDEX_ERROR_MEMORY_ALLOC =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | INDEX_MEMORY_ALLOC);
const ErrorCode INDEX_ERROR_UNMATCHED_CCINDEX_STATUS =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | UNMATCHED_CCINDEX_STATUS);
const ErrorCode INDEX_ERROR_FAIL_FOR_INVALID_HEAP_CTID =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | FAIL_FOR_INVALID_HEAP_CTID);
const ErrorCode INDEX_ERROR_FAIL_FOR_INVALID_DML_TYPE =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | FAIL_FOR_INVALID_DML_TYPE);
const ErrorCode INDEX_ERROR_FAIL_BUILD_CONCURRENTLY =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | FAIL_BUILD_CONCURRENTLY);
const ErrorCode INDEX_ERROR_INVALID_WAITING_TYPE =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | INVALID_WAITING_TYPE);
const ErrorCode INDEX_ERROR_DUPLICATE_TO_THE_SAME_RECORD =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | DUPLICATE_TO_THE_SAME_RECORD);
const ErrorCode INDEX_ERROR_EXPRESSION_VALUE_ERR =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | EXPRESSION_VALUE_ERR);
const ErrorCode INDEX_ERROR_UNEXPECTED_NULL_VALUE =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | UNEXPECTED_NULL_VALUE);
const ErrorCode INDEX_ERROR_BTREE_STRUCTURE_DAMAGED =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | BTREE_STRUCTURE_DAMAGED);
const ErrorCode INDEX_ERROR_FAIL_READ_PAGE =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | INDEX_FAIL_READ_PAGE);
const ErrorCode INDEX_ERROR_PAGE_DIFF_IN_BUFTAG =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | PAGE_DIFF_IN_BUFTAG);
const ErrorCode INDEX_ERROR_PAGE_EMPTY =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | INDEX_PAGE_EMPTY);
const ErrorCode INDEX_ERROR_PAGE_DIFF_IN_HEADER =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | PAGE_DIFF_IN_HEADER);
const ErrorCode INDEX_ERROR_PAGE_IS_NOT_BTRPAGE =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | PAGE_IS_NOT_BTRPAGE);
const ErrorCode INDEX_ERROR_PAGE_IS_NOT_INITIALIZED_AS_BTRPAGE =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | PAGE_IS_NOT_INITIALIZED_AS_BTRPAGE);
const ErrorCode INDEX_ERROR_TUPLE_DAMAGED =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | INDEX_TUPLE_DAMAGED);
const ErrorCode INDEX_ERROR_LOW_IS_GREATER_THAN_MAX_OFFSET =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | LOW_IS_GREATER_THAN_MAX_OFFSET);
const ErrorCode INDEX_ERROR_FAILED_UPDATE_BTRMETA_ROOT =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | FAILED_UPDATE_BTRMETA_ROOT);
const ErrorCode INDEX_ERROR_FAILED_TO_BROADCAST_WAITING_MESSAGE =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | FAILED_TO_BROADCAST_WAITING_MESSAGE);
const ErrorCode INDEX_ERROR_FAILED_TO_GET_SORTED_TUPLE =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | FAILED_TO_GET_SORTED_TUPLE);
const ErrorCode INDEX_ERROR_UNCOMMITTED_TUPLE_FOUND_WHEN_BUILDING =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | UNCOMMITTED_TUPLE_FOUND_WHEN_BUILDING);
const ErrorCode INDEX_ERROR_INVALID_SNAPSHOT_FOR_INDEX_BUILDING =
    (ERROR_MODULE_INDEX | ERROR_SEVERITY_ERROR | INVALID_SNAPSHOT_FOR_INDEX_BUILDING);
} /* namespace DSTORE */

#endif
