/*
 * Copyright (C) 2026 Huawei Technologies Co.,Ltd.
 *
 * dstore is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * dstore is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. if not, see <https://www.gnu.org/licenses/>.
 */

#ifndef DSTORE_BUFFER_ERROR_CODE_H
#define DSTORE_BUFFER_ERROR_CODE_H

#include "common/dstore_common_utils.h"
#include "framework/dstore_modules.h"
#include "errorcode/dstore_error_struct.h"

namespace DSTORE {

enum BufferErrorReason : uint32_t {
    NO_AVAILABLE_BUFFER_CAN_USE = 0x1,
    FAIL_TO_INVALIDATE_BASE_BUFFER = 0x2,
    FAIL_TO_INVALIDATE_CR_BUFFER = 0x3,
    FAIL_TO_INVALIDATE_MEMCHUNK = 0x4,
    FAIL_TO_RESIZE = 0x5,
    FAIL_TO_SHRINK = 0x6,
    INVALIDATION_WORKER_TIMEOUT = 0x7,
    PAGEWRITER_NOT_READY = 0x8,
    DIRTY_PAGE_QUEUE_FULL = 0x9,
    PAGE_NOT_IN_QUEUE = 0xA,
    PAGE_ALREADY_IN_QUEUE = 0xB,
    PAGEWRITER_ALREADY_CREATE = 0xC,
    BUFFER_NO_AVAILABLE_SLOT = 0xD,
    ABANDON_FLUSH = 0xE,
    CONSTRUCT_CR_NOT_DATA_PAGE = 0xF,
    BUFFER_OUT_OF_MEMORY = 0x10,
    TRY_LOCK_PAGE_CONTENT_FAIL = 0x11,
    PD_OWNER_REDIRECT = 0x12,
    PD_ENTRY_RELOCATING = 0x13,
    PD_ENTRY_INUSE = 0x14,
    OBSOLETE_PD = 0x15,
    INSERT_ANTI_CACHE_FAIL = 0x16,
    RPC_RESPONSE_TYPE_INVALID = 0x17,
    PD_BUCKET_RELOCATION_FAILURE = 0x18,
    RPC_LOCAL_NODE_DOWN = 0x19,
    RPC_REMOTE_NODE_DOWN = 0x1A,
    PD_OWNER_NODE_DOWN = 0x1B,
    PD_OWNER_UPDATE = 0x1C,
    PAGE_OWNER_NODE_DOWN = 0x1D,
    ACQUIRE_PD_BUCKET_LATCH_FAIL = 0x1E,
    ACQUIRE_GLOBAL_PAGE_LATCH_FAIL = 0x1F,
    ACQUIRE_GLOBAL_PAGE_LATCH_YIELD = 0x20,
    MEMBER_VIEW_CHANGE = 0x21,
    CREATE_PD_ENTRY_FAIL = 0x22,
    PAGE_REPLAY_IN_PROGRESS = 0x23,
    PAGE_VERSION_CHECK_FAIL = 0x24,
    CONSTRUCT_CR_AT_PAGE_OWNER_FAILED = 0x25,
    INVALIDATE_FAILED = 0x26,
    PD_OWNER_RIP = 0x27,
    OWNER_PAGE_REDIRECT = 0x28,
    RECEIVE_OUTDATED_MESSAGE = 0x29,
    ENCRYPT_FAILED = 0x2A,
    DECRYPT_FAILED = 0x2B,
    BUFFER_ERROR_MAX
};

const ErrorCode BUFFER_WARNING_NO_AVAILABLE_BUFFER_CAN_USE =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_WARNING | NO_AVAILABLE_BUFFER_CAN_USE);
const ErrorCode BUFFER_WARNING_FAIL_TO_INVALIDATE_BASE_BUFFER =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_WARNING | FAIL_TO_INVALIDATE_BASE_BUFFER);
const ErrorCode BUFFER_WARNING_FAIL_TO_INVALIDATE_CR_BUFFER =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_WARNING | FAIL_TO_INVALIDATE_CR_BUFFER);
const ErrorCode BUFFER_WARNING_FAIL_TO_INVALIDATE_MEMCHUNK =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_WARNING | FAIL_TO_INVALIDATE_MEMCHUNK);
const ErrorCode BUFFER_WARNING_FAIL_TO_RESIZE =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_WARNING | FAIL_TO_RESIZE);
const ErrorCode BUFFER_WARNING_FAIL_TO_SHRINK =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_WARNING | FAIL_TO_SHRINK);
const ErrorCode BUFFER_WARNING_INVALIDATION_WORKER_TIMEOUT =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_WARNING | INVALIDATION_WORKER_TIMEOUT);
const ErrorCode BGPAGEWRITER_WARNING_PAGEWRITER_NOT_READY =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_WARNING | PAGEWRITER_NOT_READY);
const ErrorCode BGPAGEWRITER_WARNING_DIRTY_PAGE_QUEUE_FULL =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_WARNING | DIRTY_PAGE_QUEUE_FULL);
const ErrorCode BGPAGEWRITER_ERROR_PAGE_NOT_IN_QUEUE =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_ERROR | PAGE_NOT_IN_QUEUE);
const ErrorCode BGPAGEWRITER_WARNING_PAGE_ALREADY_IN_QUEUE =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_WARNING | PAGE_ALREADY_IN_QUEUE);
const ErrorCode BGPAGEWRITER_ERROR_PAGEWRITER_ALREADY_CREATE =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_ERROR | PAGEWRITER_ALREADY_CREATE);
const ErrorCode BGPAGEWRITER_ERROR_NO_AVAILABLE_SLOT =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_ERROR | BUFFER_NO_AVAILABLE_SLOT);
const ErrorCode BGPAGEWRITER_ERROR_ABANDON_FLUSH =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_ERROR | ABANDON_FLUSH);
const ErrorCode BUFFER_INFO_CONSTRUCT_CR_NOT_DATA_PAGE =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_INFO | CONSTRUCT_CR_NOT_DATA_PAGE);
const ErrorCode BUFFER_ERROR_OUT_OF_MEMORY =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_ERROR | BUFFER_OUT_OF_MEMORY);
const ErrorCode BUFFER_INFO_TRY_LOCK_PAGE_CONTENT_FAIL =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_INFO | TRY_LOCK_PAGE_CONTENT_FAIL);
const ErrorCode BUFFER_INFO_PD_OWNER_REDIRECT =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_INFO | PD_OWNER_REDIRECT);
const ErrorCode BUFFER_INFO_PD_ENTRY_RELOCATING =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_INFO | PD_ENTRY_RELOCATING);
const ErrorCode BUFFER_INFO_PD_ENTRY_INUSE =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_INFO | PD_ENTRY_INUSE);
const ErrorCode BUFFER_INFO_OBSOLETE_PD =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_INFO | OBSOLETE_PD);
const ErrorCode BUFFER_ERROR_INSERT_ANTI_CACHE_FAIL =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_ERROR | INSERT_ANTI_CACHE_FAIL);
const ErrorCode BUFFER_ERROR_RPC_RESPONSE_TYPE_INVALID =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_ERROR | RPC_RESPONSE_TYPE_INVALID);
const ErrorCode BUFFER_ERROR_PD_BUCKET_RELOCATION_FAILURE =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_ERROR | PD_BUCKET_RELOCATION_FAILURE);
const ErrorCode BUFFER_ERROR_RPC_LOCAL_NODE_DOWN =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_ERROR | RPC_LOCAL_NODE_DOWN);
const ErrorCode BUFFER_ERROR_RPC_REMOTE_NODE_DOWN =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_ERROR | RPC_REMOTE_NODE_DOWN);
const ErrorCode BUFFER_ERROR_PD_OWNER_NODE_DOWN =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_ERROR | PD_OWNER_NODE_DOWN);
const ErrorCode BUFFER_ERROR_PD_OWNER_UPDATE =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_ERROR | PD_OWNER_UPDATE);
const ErrorCode BUFFER_ERROR_PAGE_OWNER_NODE_DOWN =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_ERROR | PAGE_OWNER_NODE_DOWN);
const ErrorCode BUFFER_ERROR_ACQUIRE_PD_BUCKET_LATCH_FAIL =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_ERROR | ACQUIRE_PD_BUCKET_LATCH_FAIL);
const ErrorCode BUFFER_ERROR_ACQUIRE_GLOBAL_PAGE_LATCH_FAIL =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_ERROR | ACQUIRE_GLOBAL_PAGE_LATCH_FAIL);
const ErrorCode BUFFER_ERROR_ACQUIRE_GLOBAL_PAGE_LATCH_YIELD =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_ERROR | ACQUIRE_GLOBAL_PAGE_LATCH_YIELD);
const ErrorCode BUFFER_ERROR_MEMBER_VIEW_CHANGE =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_ERROR | MEMBER_VIEW_CHANGE);
const ErrorCode BUFFER_ERROR_CREATE_PD_ENTRY_FAIL =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_ERROR | CREATE_PD_ENTRY_FAIL);
const ErrorCode BUFFER_ERROR_PAGE_REPLAY_IN_PROGRESS =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_ERROR | PAGE_REPLAY_IN_PROGRESS);
const ErrorCode BUFFER_ERROR_PAGE_VERSION_CHECK_FAIL =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_ERROR | PAGE_VERSION_CHECK_FAIL);
const ErrorCode BUFFER_ERROR_CONSTRUCT_CR_AT_PAGE_OWNER_FAILED =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_ERROR | CONSTRUCT_CR_AT_PAGE_OWNER_FAILED);
const ErrorCode BUFFER_ERROR_INVALIDATE_FAILED =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_ERROR | INVALIDATE_FAILED);
const ErrorCode BUFFER_INFO_PD_OWNER_RIP =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_INFO | PD_OWNER_RIP);
const ErrorCode BUFFER_INFO_OWNER_PAGE_REDIRECT =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_INFO | OWNER_PAGE_REDIRECT);
const ErrorCode BUFFER_INFO_RECEIVE_OUTDATED_MESSAGE =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_INFO | RECEIVE_OUTDATED_MESSAGE);
const ErrorCode TDE_ERROR_ENCRYPT_FAILED =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_ERROR | ENCRYPT_FAILED);
const ErrorCode TDE_ERROR_DECRYPT_FAILED =
    (ERROR_MODULE_BUFFER | ERROR_SEVERITY_ERROR | DECRYPT_FAILED);

} /* namespace DSTORE */

#endif
