/*
 * Copyright (C) 2026 Huawei Technologies Co.,Ltd.
 *
 * dstore is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * dstore is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. if not, see <https://www.gnu.org/licenses/>.
 */

#ifndef DSTORE_LOCK_ERROR_CODE_H
#define DSTORE_LOCK_ERROR_CODE_H

#include "common/dstore_common_utils.h"
#include "framework/dstore_modules.h"
#include "errorcode/dstore_error_struct.h"

namespace DSTORE {

enum LockErrorReason : uint32_t {
    LOCK_NOT_AVAIL = 0x1,
    LOCK_DEADLOCK = 0x2,
    LOCK_OUT_OF_MEMORY = 0x3,
    LOCK_MEMORY_OPERATE = 0x4,
    LOCK_WAITING = 0x5,
    LOCK_INVALID_PARAMETER = 0x6,
    ADVISORY_NOT_HELD = 0x7,
    LOCK_WAIT_TIMEOUT = 0x8,
    LOCK_WAIT_CANCELED = 0x9,
    LOCK_THREAD_NOT_FOUND = 0xA,
    TRANSFER_LOCK_NOT_HELD = 0xB,
    LOCK_NOT_AVAIL_NAME = 0xC,
    TOO_MANY_READERS_WRITERS = 0xD,
    LOCK_FREEZING = 0xE,
    LOCK_RELOCATING = 0xF,
    LOCK_NOT_LOCAL = 0x10,
    RELOCATION_VALID_BUCKET = 0x11,
    ZONELOCK_TRANSFER_REJECTED = 0x12,
    LOCK_NODE_FAIL = 0x13,
    BUCKET_RELOCATION_FAILURE = 0x14,
    BUCKET_RECOVERY_IN_PROGRESS_FAILURE = 0x15,
    BUCKET_RECOVERY_VALID_FAILURE = 0x16,
    RPC_MESSAGE_PARSER_FAILURE = 0x17,
    LOCK_RECOVERY_FAILURE = 0x18,
    LOCK_NOT_SUPPORTED = 0x19,
    LOCK_SCAN_PASSED = 0x1A,
    WAIT_SPECIFY_TIMEOUT = 0x1B,
    LOCK_ERROR_MAX
};

const ErrorCode LOCK_INFO_NOT_AVAIL =
    (ERROR_MODULE_LOCK | ERROR_SEVERITY_INFO | LOCK_NOT_AVAIL);
const ErrorCode LOCK_ERROR_DEADLOCK =
    (ERROR_MODULE_LOCK | ERROR_SEVERITY_ERROR | LOCK_DEADLOCK);
const ErrorCode LOCK_ERROR_OUT_OF_MEMORY =
    (ERROR_MODULE_LOCK | ERROR_SEVERITY_ERROR | LOCK_OUT_OF_MEMORY);
const ErrorCode LOCK_ERROR_MEMORY_OPERATE =
    (ERROR_MODULE_LOCK | ERROR_SEVERITY_ERROR | LOCK_MEMORY_OPERATE);
const ErrorCode LOCK_INFO_WAITING =
    (ERROR_MODULE_LOCK | ERROR_SEVERITY_INFO | LOCK_WAITING);
const ErrorCode LOCK_ERROR_INVALID_PARAMETER =
    (ERROR_MODULE_LOCK | ERROR_SEVERITY_ERROR | LOCK_INVALID_PARAMETER);
const ErrorCode LOCK_ERROR_ADVISORY_NOT_HELD =
    (ERROR_MODULE_LOCK | ERROR_SEVERITY_ERROR | ADVISORY_NOT_HELD);
const ErrorCode LOCK_ERROR_WAIT_TIMEOUT =
    (ERROR_MODULE_LOCK | ERROR_SEVERITY_ERROR | LOCK_WAIT_TIMEOUT);
const ErrorCode LOCK_ERROR_WAIT_CANCELED =
    (ERROR_MODULE_LOCK | ERROR_SEVERITY_ERROR | LOCK_WAIT_CANCELED);
const ErrorCode LOCK_ERROR_THREAD_NOT_FOUND =
    (ERROR_MODULE_LOCK | ERROR_SEVERITY_ERROR | LOCK_THREAD_NOT_FOUND);
const ErrorCode XACTLOCK_ERROR_TRANSFER_LOCK_NOT_HELD =
    (ERROR_MODULE_LOCK | ERROR_SEVERITY_ERROR | TRANSFER_LOCK_NOT_HELD);
const ErrorCode LWLOCK_ERROR_NOT_AVAIL_NAME =
    (ERROR_MODULE_LOCK | ERROR_SEVERITY_ERROR | LOCK_NOT_AVAIL_NAME);
const ErrorCode RWLOCK_WARNING_TOO_MANY_READERS_WRITERS =
    (ERROR_MODULE_LOCK | ERROR_SEVERITY_WARNING | TOO_MANY_READERS_WRITERS);
const ErrorCode LOCK_WARNING_FREEZING =
    (ERROR_MODULE_LOCK | ERROR_SEVERITY_WARNING | LOCK_FREEZING);
const ErrorCode LOCK_INFO_RELOCATING =
    (ERROR_MODULE_LOCK | ERROR_SEVERITY_INFO | LOCK_RELOCATING);
const ErrorCode LOCK_INFO_LOCK_NOT_LOCAL =
    (ERROR_MODULE_LOCK | ERROR_SEVERITY_INFO | LOCK_NOT_LOCAL);
const ErrorCode LOCK_INFO_RELOCATION_VALID_BUCKET =
    (ERROR_MODULE_LOCK | ERROR_SEVERITY_INFO | RELOCATION_VALID_BUCKET);
const ErrorCode LOCK_INFO_ZONELOCK_TRANSFER_REJECTED =
    (ERROR_MODULE_LOCK | ERROR_SEVERITY_INFO | ZONELOCK_TRANSFER_REJECTED);
const ErrorCode LOCK_ERROR_NODE_FAIL =
    (ERROR_MODULE_LOCK | ERROR_SEVERITY_ERROR | LOCK_NODE_FAIL);
const ErrorCode LOCK_ERROR_BUCKET_RELOCATION_FAILURE =
    (ERROR_MODULE_LOCK | ERROR_SEVERITY_ERROR | BUCKET_RELOCATION_FAILURE);
const ErrorCode LOCK_ERROR_BUCKET_RECOVERY_IN_PROGRESS_FAILURE =
    (ERROR_MODULE_LOCK | ERROR_SEVERITY_ERROR | BUCKET_RECOVERY_IN_PROGRESS_FAILURE);
const ErrorCode LOCK_ERROR_BUCKET_RECOVERY_VALID_FAILURE =
    (ERROR_MODULE_LOCK | ERROR_SEVERITY_ERROR | BUCKET_RECOVERY_VALID_FAILURE);
const ErrorCode LOCK_ERROR_RPC_MESSAGE_PARSER_FAILURE =
    (ERROR_MODULE_LOCK | ERROR_SEVERITY_ERROR | RPC_MESSAGE_PARSER_FAILURE);
const ErrorCode LOCK_ERROR_RECOVERY_FAILURE =
    (ERROR_MODULE_LOCK | ERROR_SEVERITY_ERROR | LOCK_RECOVERY_FAILURE);
const ErrorCode LOCK_ERROR_NOT_SUPPORTED =
    (ERROR_MODULE_LOCK | ERROR_SEVERITY_ERROR | LOCK_NOT_SUPPORTED);
const ErrorCode LOCK_ERROR_SCAN_PASSED =
    (ERROR_MODULE_LOCK | ERROR_SEVERITY_ERROR | LOCK_SCAN_PASSED);
const ErrorCode LOCK_ERROR_WAIT_SPECIFY_TIMEOUT =
    (ERROR_MODULE_LOCK | ERROR_SEVERITY_ERROR | WAIT_SPECIFY_TIMEOUT);

} /* namespace DSTORE */

#endif
