/*
 * Copyright (C) 2026 Huawei Technologies Co.,Ltd.
 *
 * dstore is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * dstore is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. if not, see <https://www.gnu.org/licenses/>.
 */

#ifndef DSTORE_LOGICAL_REPLICATION_ERROR_CODE_H
#define DSTORE_LOGICAL_REPLICATION_ERROR_CODE_H

#include "common/dstore_common_utils.h"
#include "framework/dstore_modules.h"
#include "errorcode/dstore_error_struct.h"

namespace DSTORE {

enum DecodeErrorReason : uint32_t {
    PLUGIN_LOAD_ERROR = 0x1,
    DICT_NOT_FOUND = 0x2,
    DECODE_UNSUPPORT_TYPE = 0x3,
    DECODE_EMPTY_TRX = 0x4,
    UNSUPPORTED_ATTR_TYPE = 0x5,
    DECODE_CONTEXT_CREATE_ERROR = 0x6,
    DECODE_DUPLICATE_SLOT = 0x7,
    DECODE_SLOT_EXCEED_MAX_NUM = 0x8,
    DECODE_SLOT_NOT_FOUND = 0x9,
    DECODE_SLOT_IS_ACTIVE = 0xA,
    DECODE_HANDLER_NO_MEM = 0xB,
    DECODE_CTX_INIT_FAIL = 0xC,
    DISTRIBUTE_DECODE_HANDLER_EMPTY = 0xD,
    DECODE_ERROR_MAX
};

const ErrorCode DECODE_INFO_PLUGIN_LOAD_ERROR =
    (ERROR_MODULE_LOGICAL_REPLICATION | ERROR_SEVERITY_INFO | PLUGIN_LOAD_ERROR);
const ErrorCode DECODE_ERROR_DICT_NOT_FOUND =
    (ERROR_MODULE_LOGICAL_REPLICATION | ERROR_SEVERITY_ERROR | DICT_NOT_FOUND);
const ErrorCode DECODE_ERROR_UNSUPPORT_TYPE =
    (ERROR_MODULE_LOGICAL_REPLICATION | ERROR_SEVERITY_ERROR | DECODE_UNSUPPORT_TYPE);
const ErrorCode DECODE_ERROR_EMPTY_TRX =
    (ERROR_MODULE_LOGICAL_REPLICATION | ERROR_SEVERITY_ERROR | DECODE_EMPTY_TRX);
const ErrorCode DECODE_ERROR_UNSUPPORTED_ATTR_TYPE =
    (ERROR_MODULE_LOGICAL_REPLICATION | ERROR_SEVERITY_ERROR | UNSUPPORTED_ATTR_TYPE);
const ErrorCode DECODE_ERROR_CONTEXT_CREATE_ERROR =
    (ERROR_MODULE_LOGICAL_REPLICATION | ERROR_SEVERITY_ERROR | DECODE_CONTEXT_CREATE_ERROR);
const ErrorCode DECODE_ERROR_DUPLICATE_SLOT =
    (ERROR_MODULE_LOGICAL_REPLICATION | ERROR_SEVERITY_ERROR | DECODE_DUPLICATE_SLOT);
const ErrorCode DECODE_ERROR_SLOT_EXCEED_MAX_NUM =
    (ERROR_MODULE_LOGICAL_REPLICATION | ERROR_SEVERITY_ERROR | DECODE_SLOT_EXCEED_MAX_NUM);
const ErrorCode DECODE_ERROR_SLOT_NOT_FOUND =
    (ERROR_MODULE_LOGICAL_REPLICATION | ERROR_SEVERITY_ERROR | DECODE_SLOT_NOT_FOUND);
const ErrorCode DECODE_ERROR_SLOT_IS_ACTIVE =
    (ERROR_MODULE_LOGICAL_REPLICATION | ERROR_SEVERITY_ERROR | DECODE_SLOT_IS_ACTIVE);
const ErrorCode DECODE_ERROR_DECODE_HANDLER_NO_MEM =
    (ERROR_MODULE_LOGICAL_REPLICATION | ERROR_SEVERITY_ERROR | DECODE_HANDLER_NO_MEM);
const ErrorCode DECODE_ERROR_DECODE_CTX_INIT_FAIL =
    (ERROR_MODULE_LOGICAL_REPLICATION | ERROR_SEVERITY_ERROR | DECODE_CTX_INIT_FAIL);
const ErrorCode DECODE_ERROR_DISTRIBUTE_DECODE_HANDLER_EMPTY =
    (ERROR_MODULE_LOGICAL_REPLICATION | ERROR_SEVERITY_ERROR | DISTRIBUTE_DECODE_HANDLER_EMPTY);

} /* namespace DSTORE */

#endif
