/*
 * Copyright (C) 2026 Huawei Technologies Co.,Ltd.
 *
 * dstore is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * dstore is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. if not, see <https://www.gnu.org/licenses/>.
 */

#ifndef DSTORE_COMMON_ERROR_CODE_H
#define DSTORE_COMMON_ERROR_CODE_H

#include "common/dstore_common_utils.h"
#include "framework/dstore_modules.h"
#include "errorcode/dstore_error_struct.h"

namespace DSTORE {

enum CommonErrorReason : uint32_t {
    UNDEFINED_ERROR = 0x1,
    NODE_UNREACHEABLE = 0x2,
    MEMORY_ALLOCATION = 0x3,
    CONTACT_ENGINEER = 0x4,
    FUNCTION_RETURN_NULL = 0x5,
    CREATE_THREAD_FAIL = 0x6,
    INIT_THREAD_FAIL = 0x7,
    NO_ACTIVE_NODE = 0x8,
    UNEXPECTED_END_OF_DATA = 0x9,
    RANDOM_ACCESS_DISALLOWED = 0xA,
    INSUFFICIENT_MEMORY_ALLOWED = 0xB,
    MISSING_SUPPORT_FUNCTION_FOR_TYPE = 0xC,
    MISSING_SUPPORT_FUNCTION_FOR_FUNCOID = 0xD,
    UNEXPECTED_SORT_SUPPORT_STRATEGY = 0xE,
    UNEXPECTED_OUT_OF_MEMORY = 0xF,
    INVALID_TUPLESORT_STATE = 0x10,
    TOO_MANY_TUPLE = 0x11,
    UNEXPECTED_TAPE_POSITION = 0x12,
    BOGUS_TUPLE_LENGTH = 0x13,
    TUPLESORT_UNEXPECTED_END_OF_TAPE = 0x14,
    COULD_NOT_CREATE_UNIQUE_INDEX = 0x15,
    SHOULD_NOT_BE_CALLED = 0x16,
    TOO_MANY_RUNS_FOR_EXTERNAL_SORT = 0x17,
    BEGIN_INDEX_SORT = 0x18,
    SORT_DONE = 0x19,
    SWITCH_TO_BOUNDED_HEAPSORT = 0x1A,
    PERFORM_SORT_START = 0x1B,
    FINAL_MERGE = 0x1C,
    PERFORM_SORT_DONE = 0x1D,
    SWITCH_TO_EXTERNAL_SORT = 0x1E,
    WORKER_USE_MEMORY = 0x1F,
    START_MERGE_PASS = 0x20,
    START_QUICKSORT = 0x21,
    FINISH_QUICKSORT = 0x22,
    FINISH_WRITE_RUN = 0x23,
    NO_DATA_LEFT_IN_MESSAGE = 0x24,
    INSUFFICIENT_DATA_LEFT = 0x25,
    SPIN_NOT_SUPPORT = 0x26,
    INVALID_DATUM_POINTER = 0x27,
    INVALID_TYPLEN = 0x28,
    INVALID_CHARACTER_VALUE_FOR_CAST = 0x29,
    INDETERMINATE_COLLATION = 0x2A,
    INVALID_STRING_ENLARGE = 0x2B,
    CANNOT_ENLARGE_BUFFER = 0x2C,
    CANNOT_COMPARE_UNICODE_STRINGS = 0x2D,
    NULL_VALUE_NOT_ALLOWED = 0x2E,
    DATATYPE_MISMATCH = 0x2F,
    ARRAY_SIZE_EXCEED_LIMIT = 0x30,
    DOUBLY_NOT_NULL_VIOLATION = 0x31,
    SINGLY_NOT_NULL_VIOLATION = 0x32,
    DOUBLY_DATA_CORRUPTED = 0x33,
    FAIL_CREATE_SEMA = 0x34,
    FAIL_SYSTEM_CALL_SEMGET = 0x35,
    WHY_CREATE_SEMA_FAIL = 0x36,
    SEMCTL_FAIL = 0x37,
    RAISE_SEMVMX_VALUE = 0x38,
    TOO_MANY_SEMAPHORES_CREATED = 0x39,
    SEMOP_FAIL = 0x3A,
    FUTEX_FAIL = 0x3B,
    COULD_NOT_SEEK_BLOCK = 0x3C,
    COULD_NOT_SEEK_BLOCK_READONLY = 0x3D,
    INVALID_LOGTAPE_STATE = 0x3E,
    LOGTAPE_UNEXPECTED_END_OF_TAPE = 0x3F,
    BROKEN_TAPE = 0x40,
    INVALID_TAPE_SEEK_POSITION = 0x41,
    MEMORY_SIZE_OVERFLOW = 0x42,
    HASH_OUT_OF_MEMORY = 0x43,
    OUT_OF_SHARED_MEMORY = 0x44,
    FAIL_TO_INITIALIZE_TABLE = 0x45,
    DIVISION_BY_ZERO = 0x46,
    CANNOT_INSERT_INTO_FROZEN = 0x47,
    UNRECOGNIZED_HASH_ACTION_CODE = 0x48,
    CANNOT_FREEZE_SHARED_HASHTABLE = 0x49,
    CANNOT_FREEZE_ACTIVE_HASHTABLE = 0x4A,
    CANNOT_TOO_MANY_ACTIVE_HASH_SEQ_SEARCH_SCAN = 0x4B,
    NO_HASH_SEQ_SEARCH_SCAN = 0x4C,
    LEAKED_HASH_SEQ_SEARCH_SCAN = 0x4D,
    OUT_OF_BINARY_HEAP_SLOTS = 0x4E,
    UNSUPPORTED_BYVAL_LENGTH = 0x4F,
    COMMON_INTERNAL = 0x50,
    RPC_OUT_OF_MEMORY = 0x51,
    BAD_CONNECTION = 0x52,
    COMMON_INVALID_NODE_ID = 0x53,
    REJECTED_BY_HIGHER_TERM = 0x54,
    REQUEST_ARE_CANCELED = 0x55,
    FAIL_CREATE_TEMP_FILE = 0x56,
    FAIL_WRITE_TEMP_FILE = 0x57,
    BUFFER_FAIL_READ_PAGE = 0x58,
    CONNECTION_HEART_BEAT_TIMEOUT = 0x59,
    TUPLESIZE_LIMIT_EXCEEDED = 0x5A,
    FAIL_CHECK_INVALID_COMPLETION = 0x5B,
    COMMON_ERROR_REASON_MAX
};

const ErrorCode COMMON_ERROR_UNDEFINED_ERROR =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | UNDEFINED_ERROR);
const ErrorCode COMMON_ERROR_NODE_UNREACHEABLE =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | NODE_UNREACHEABLE);
const ErrorCode COMMON_ERROR_MEMORY_ALLOCATION =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | MEMORY_ALLOCATION);
const ErrorCode COMMON_INFO_CONTACT_ENGINEER =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_INFO | CONTACT_ENGINEER);
const ErrorCode COMMON_ERROR_FUNCTION_RETURN_NULL =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | FUNCTION_RETURN_NULL);
const ErrorCode COMMON_ERROR_CREATE_THREAD_FAIL =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | CREATE_THREAD_FAIL);
const ErrorCode COMMON_ERROR_INIT_THREAD_FAIL =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | INIT_THREAD_FAIL);
const ErrorCode COMMON_ERROR_NO_ACTIVE_NODE =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | NO_ACTIVE_NODE);
const ErrorCode TUPLESORT_ERROR_UNEXPECTED_END_OF_DATA =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | UNEXPECTED_END_OF_DATA);
const ErrorCode TUPLESORT_ERROR_RANDOM_ACCESS_DISALLOWED =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | RANDOM_ACCESS_DISALLOWED);
const ErrorCode TUPLESORT_ERROR_INSUFFICIENT_MEMORY_ALLOWED =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | INSUFFICIENT_MEMORY_ALLOWED);
const ErrorCode TUPLESORT_ERROR_MISSING_SUPPORT_FUNCTION_FOR_TYPE =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | MISSING_SUPPORT_FUNCTION_FOR_TYPE);
const ErrorCode TUPLESORT_ERROR_MISSING_SUPPORT_FUNCTION_FOR_FUNCOID =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | MISSING_SUPPORT_FUNCTION_FOR_FUNCOID);
const ErrorCode TUPLESORT_ERROR_UNEXPECTED_SORT_SUPPORT_STRATEGY =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | UNEXPECTED_SORT_SUPPORT_STRATEGY);
const ErrorCode TUPLESORT_ERROR_UNEXPECTED_OUT_OF_MEMORY =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | UNEXPECTED_OUT_OF_MEMORY);
const ErrorCode TUPLESORT_ERROR_INVALID_TUPLESORT_STATE =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | INVALID_TUPLESORT_STATE);
const ErrorCode TUPLESORT_ERROR_TOO_MANY_TUPLE =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | TOO_MANY_TUPLE);
const ErrorCode TUPLESORT_ERROR_UNEXPECTED_TAPE_POSITION =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | UNEXPECTED_TAPE_POSITION);
const ErrorCode TUPLESORT_ERROR_BOGUS_TUPLE_LENGTH =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | BOGUS_TUPLE_LENGTH);
const ErrorCode TUPLESORT_ERROR_UNEXPECTED_END_OF_TAPE =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | TUPLESORT_UNEXPECTED_END_OF_TAPE);
const ErrorCode TUPLESORT_ERROR_COULD_NOT_CREATE_UNIQUE_INDEX =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | COULD_NOT_CREATE_UNIQUE_INDEX);
const ErrorCode TUPLESORT_ERROR_SHOULD_NOT_BE_CALLED =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | SHOULD_NOT_BE_CALLED);
const ErrorCode TUPLESORT_ERROR_TOO_MANY_RUNS_FOR_EXTERNAL_SORT =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | TOO_MANY_RUNS_FOR_EXTERNAL_SORT);
const ErrorCode TUPLESORT_INFO_BEGIN_INDEX_SORT =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_INFO | BEGIN_INDEX_SORT);
const ErrorCode TUPLESORT_INFO_SORT_DONE =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_INFO | SORT_DONE);
const ErrorCode TUPLESORT_INFO_SWITCH_TO_BOUNDED_HEAPSORT =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_INFO | SWITCH_TO_BOUNDED_HEAPSORT);
const ErrorCode TUPLESORT_INFO_PERFORM_SORT_START =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_INFO | PERFORM_SORT_START);
const ErrorCode TUPLESORT_INFO_FINAL_MERGE =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_INFO | FINAL_MERGE);
const ErrorCode TUPLESORT_INFO_PERFORM_SORT_DONE =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_INFO | PERFORM_SORT_DONE);
const ErrorCode TUPLESORT_INFO_SWITCH_TO_EXTERNAL_SORT =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_INFO | SWITCH_TO_EXTERNAL_SORT);
const ErrorCode TUPLESORT_INFO_WORKER_USE_MEMORY =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_INFO | WORKER_USE_MEMORY);
const ErrorCode TUPLESORT_INFO_START_MERGE_PASS =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_INFO | START_MERGE_PASS);
const ErrorCode TUPLESORT_INFO_START_QUICKSORT =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_INFO | START_QUICKSORT);
const ErrorCode TUPLESORT_INFO_FINISH_QUICKSORT =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_INFO | FINISH_QUICKSORT);
const ErrorCode TUPLESORT_INFO_FINISH_WRITE_RUN =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_INFO | FINISH_WRITE_RUN);
const ErrorCode STRING_ERROR_NO_DATA_LEFT_IN_MESSAGE =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | NO_DATA_LEFT_IN_MESSAGE);
const ErrorCode STRING_ERROR_INSUFFICIENT_DATA_LEFT =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | INSUFFICIENT_DATA_LEFT);
const ErrorCode STRING_WARNING_SPIN_NOT_SUPPORT =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_WARNING | SPIN_NOT_SUPPORT);
const ErrorCode DATATYPE_ERROR_INVALID_DATUM_POINTER =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | INVALID_DATUM_POINTER);
const ErrorCode DATATYPE_ERROR_INVALID_TYPLEN =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | INVALID_TYPLEN);
const ErrorCode DATATYPE_ERROR_INVALID_CHARACTER_VALUE_FOR_CAST =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | INVALID_CHARACTER_VALUE_FOR_CAST);
const ErrorCode DATATYPE_ERROR_INDETERMINATE_COLLATION =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | INDETERMINATE_COLLATION);
const ErrorCode STRING_ERROR_INVALID_STRING_ENLARGE =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | INVALID_STRING_ENLARGE);
const ErrorCode STRING_ERROR_CANNOT_ENLARGE_BUFFER =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | CANNOT_ENLARGE_BUFFER);
const ErrorCode STRING_ERROR_CANNOT_COMPARE_UNICODE_STRINGS =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | CANNOT_COMPARE_UNICODE_STRINGS);
const ErrorCode ARRAY_ERROR_NULL_VALUE_NOT_ALLOWED =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | NULL_VALUE_NOT_ALLOWED);
const ErrorCode ARRAY_ERROR_DATATYPE_MISMATCH =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | DATATYPE_MISMATCH);
const ErrorCode ARRAY_ERROR_ARRAY_SIZE_EXCEED_LIMIT =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | ARRAY_SIZE_EXCEED_LIMIT);
const ErrorCode LIST_ERROR_DOUBLY_NOT_NULL_VIOLATION =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | DOUBLY_NOT_NULL_VIOLATION);
const ErrorCode LIST_ERROR_SINGLY_NOT_NULL_VIOLATION =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | SINGLY_NOT_NULL_VIOLATION);
const ErrorCode LIST_ERROR_DOUBLY_DATA_CORRUPTED =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | DOUBLY_DATA_CORRUPTED);
const ErrorCode SYSVSEMA_FATAL_FAIL_CREATE_SEMA =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_FATAL | FAIL_CREATE_SEMA);
const ErrorCode SYSVSEMA_FATAL_FAIL_SYSTEM_CALL_SEMGET =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_FATAL | FAIL_SYSTEM_CALL_SEMGET);
const ErrorCode SYSVSEMA_INFO_WHY_CREATE_SEMA_FAIL =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_INFO | WHY_CREATE_SEMA_FAIL);
const ErrorCode SYSVSEMA_FATAL_SEMCTL_FAIL =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_FATAL | SEMCTL_FAIL);
const ErrorCode SYSVSEMA_INFO_RAISE_SEMVMX_VALUE =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_INFO | RAISE_SEMVMX_VALUE);
const ErrorCode SYSVSEMA_FATAL_TOO_MANY_SEMAPHORES_CREATED =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_FATAL | TOO_MANY_SEMAPHORES_CREATED);
const ErrorCode SYSVSEM_FATAL_SEMOP_FAIL =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_FATAL | SEMOP_FAIL);
const ErrorCode SYSTEM_FATAL_FUTEX_FAIL =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_FATAL | FUTEX_FAIL);
const ErrorCode LOGTAPE_ERROR_COULD_NOT_SEEK_BLOCK =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | COULD_NOT_SEEK_BLOCK);
const ErrorCode LOGTAPE_ERROR_COULD_NOT_SEEK_BLOCK_READONLY =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | COULD_NOT_SEEK_BLOCK_READONLY);
const ErrorCode LOGTAPE_ERROR_INVALID_LOGTAPE_STATE =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | INVALID_LOGTAPE_STATE);
const ErrorCode LOGTAPE_ERROR_UNEXPECTED_END_OF_TAPE =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | LOGTAPE_UNEXPECTED_END_OF_TAPE);
const ErrorCode LOGTAPE_ERROR_BROKEN_TAPE =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | BROKEN_TAPE);
const ErrorCode LOGTAPE_ERROR_INVALID_TAPE_SEEK_POSITION =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | INVALID_TAPE_SEEK_POSITION);
const ErrorCode HASH_ERROR_MEMORY_SIZE_OVERFLOW =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | MEMORY_SIZE_OVERFLOW);
const ErrorCode HASH_ERROR_OUT_OF_MEMORY =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | HASH_OUT_OF_MEMORY);
const ErrorCode HASH_ERROR_OUT_OF_SHARED_MEMORY =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | OUT_OF_SHARED_MEMORY);
const ErrorCode HASH_ERROR_FAIL_TO_INITIALIZE_TABLE =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | FAIL_TO_INITIALIZE_TABLE);
const ErrorCode HASH_ERROR_DIVISION_BY_ZERO =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | DIVISION_BY_ZERO);
const ErrorCode HASH_ERROR_CANNOT_INSERT_INTO_FROZEN =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | CANNOT_INSERT_INTO_FROZEN);
const ErrorCode HASH_ERROR_UNRECOGNIZED_HASH_ACTION_CODE =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | UNRECOGNIZED_HASH_ACTION_CODE);
const ErrorCode HASH_ERROR_CANNOT_FREEZE_SHARED_HASHTABLE =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | CANNOT_FREEZE_SHARED_HASHTABLE);
const ErrorCode HASH_ERROR_CANNOT_FREEZE_ACTIVE_HASHTABLE =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | CANNOT_FREEZE_ACTIVE_HASHTABLE);
const ErrorCode HASH_ERROR_CANNOT_TOO_MANY_ACTIVE_HASH_SEQ_SEARCH_SCAN =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | CANNOT_TOO_MANY_ACTIVE_HASH_SEQ_SEARCH_SCAN);
const ErrorCode HASH_ERROR_NO_HASH_SEQ_SEARCH_SCAN =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | NO_HASH_SEQ_SEARCH_SCAN);
const ErrorCode HASH_WARNING_LEAKED_HASH_SEQ_SEARCH_SCAN =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_WARNING | LEAKED_HASH_SEQ_SEARCH_SCAN);
const ErrorCode BINARYHEAP_ERROR_OUT_OF_BINARY_HEAP_SLOTS =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | OUT_OF_BINARY_HEAP_SLOTS);
const ErrorCode ATTRIBUTE_ERROR_UNSUPPORTED_BYVAL_LENGTH =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | UNSUPPORTED_BYVAL_LENGTH);
const ErrorCode RPC_ERROR_INTERNAL =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | COMMON_INTERNAL);
const ErrorCode RPC_ERROR_OUT_OF_MEMORY =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | RPC_OUT_OF_MEMORY);
const ErrorCode RPC_ERROR_BAD_CONNECTION =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | BAD_CONNECTION);
const ErrorCode RPC_ERROR_INVALID_NODE_ID =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | COMMON_INVALID_NODE_ID);
const ErrorCode RPC_ERROR_REJECTED_BY_HIGHER_TERM =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | REJECTED_BY_HIGHER_TERM);
const ErrorCode SQL_WARNING_REQUEST_ARE_CANCELED =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_WARNING | REQUEST_ARE_CANCELED);
const ErrorCode BUFFILE_ERROR_FAIL_CREATE_TEMP_FILE =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | FAIL_CREATE_TEMP_FILE);
const ErrorCode BUFFILE_ERROR_FAIL_WRITE_TEMP_FILE =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | FAIL_WRITE_TEMP_FILE);
const ErrorCode BUFFER_ERROR_FAIL_READ_PAGE =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | BUFFER_FAIL_READ_PAGE);
const ErrorCode RPC_ERROR_CONNECTION_HEART_BEAT_TIMEOUT =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | CONNECTION_HEART_BEAT_TIMEOUT);
const ErrorCode COMMON_ERROR_TUPLESIZE_LIMIT_EXCEEDED =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | TUPLESIZE_LIMIT_EXCEEDED);
const ErrorCode INVALID_ERROR_FAIL_CHECK_INVALID_COMPLETION =
    (ERROR_MODULE_COMMON | ERROR_SEVERITY_ERROR | FAIL_CHECK_INVALID_COMPLETION);

} /* namespace DSTORE */

#endif
