/*
 * Copyright (C) 2026 Huawei Technologies Co.,Ltd.
 *
 * dstore is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * dstore is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. if not, see <https://www.gnu.org/licenses/>.
 */

#ifndef DSTORE_LWLOCK_DIAGNOSE_H
#define DSTORE_LWLOCK_DIAGNOSE_H

namespace DSTORE {
#pragma GCC visibility push(default)
class LWLockDiagnose {
public:
    /**
     * Get LWLock waiting and holding information by thread.
     */
    static char *GetLWLockStatus(void);
    static const char *GetGroupName(uint32_t group_id);
};

enum LWLockGroupIds {
    LWLOCK_GROUP_DEFAULT = 0,
    LWLOCK_GROUP_HASH_TABLE_PARTITION,
    LWLOCK_GROUP_TABLE_LOCK_STAT_MUTEX,
    LWLOCK_GROUP_BUF_LRU,
    LWLOCK_GROUP_DISTRIBUTED_BUF_DESC_CONTROLLER_PD_REQUEST,
    LWLOCK_GROUP_INV_TASK_QUEUE,
    LWLOCK_GROUP_REGISTERED_THREAD,
    LWLOCK_GROUP_MEMBER_VIEW_ON_CHANGE,
    LWLOCK_GROUP_MEMBER_VIEW_NODE_CRASH_TERM_HTAB,
    LWLOCK_GROUP_DEADLOCK_DETECTOR_WAITER_INFO,
    LWLOCK_GROUP_DISTRIBUTED_TABLE_CLUSTER_INFO,
    LWLOCK_GROUP_THREAD_LIST,
    LWLOCK_GROUP_CSN_NODELIST_UPDATE,
    LWLOCK_GROUP_PLSN_WAIT,
    LWLOCK_GROUP_BUF_DESC_IO_IN_PROGRESS,
    LWLOCK_GROUP_BUF_DESC_CR_ASSIGN,
    LWLOCK_GROUP_BUF_DESC_PAGE_WRITE_WAL,
    LWLOCK_GROUP_BUF_DESC_CONTENT,
    LWLOCK_GROUP_BUF_LRU_EXPAND,
    LWLOCK_GROUP_BUF_MEMCHUNK,
    LWLOCK_GROUP_BUF_MEMCHUNK_LIST,
    LWLOCK_GROUP_BUF_MGR_SIZE,
    LWLOCK_GROUP_BUF_MAPPING,
    LWLOCK_GROUP_CHECK_POINT,
    LWLOCK_GROUP_MEM_CHECK_POINT,
    LWLOCK_GROUP_BUFFER_POOL_SCAN_MEM_CHUNK,
    LWLOCK_GROUP_PD_HASH_PARTITION,
    LWLOCK_GROUP_CONSISTENT_HASH_LIST_LATCH,
    LWLOCK_GROUP_HASH_META_LATCH,
    LWLOCK_GROUP_HASH_RING_LATCH,
    LWLOCK_GROUP_RESCUE_MEM,
    LWLOCK_GROUP_VFS_LIB_HANDLE,
    LWLOCK_GROUP_PDB_INDEX,
    LWLOCK_GROUP_INIT_PDB,
    LWLOCK_GROUP_THREAD_CORE,
    LWLOCK_GROUP_THREAD_XACT,
    LWLOCK_GROUP_AID_CLUSTER,
    LWLOCK_GROUP_DEADLOCK_DETECT,
    LWLOCK_GROUP_DEADLOCK_THRD_STAT,
    LWLOCK_GROUP_DEADLOCK_DETECT_DATA,
    LWLOCK_GROUP_LOCAL_LOCK,
    LWLOCK_GROUP_LOCK_NODE_LOCAL_PARTITION,
    LWLOCK_GROUP_DECODE_DICT_BUF,
    LWLOCK_GROUP_LOGICAL_REPLICA_MGR_SLOT_CTL,
    LWLOCK_GROUP_LOGICAL_REPLICA_MGR_SLOT_ALLOC,
    LWLOCK_GROUP_DISTRIBUTE_LOGICAL_REPLICA_MGR_NODE_LIST,
    LWLOCK_GROUP_PDB_COMM_STATUS,
    LWLOCK_GROUP_ALLOC_STANDBY_PDB_SLOT,
    LWLOCK_GROUP_PDB_REPLICA_MGR_NODE_LIST,
    LWLOCK_GROUP_PERF_DUMP,
    LWLOCK_GROUP_DIST_PDB_RECOVERY_STATE,
    LWLOCK_GROUP_MULTI_THREAD_TASK_HTAB,
    LWLOCK_GROUP_REDO_QUEUE,
    LWLOCK_GROUP_REDO_QUEUE_HTAB_PARTITION,
    LWLOCK_GROUP_OBJ_SPACE_MGR_TASK_QUEUE,
    LWLOCK_GROUP_TBS_PAGE,
    LWLOCK_GROUP_TBS_PAGE_MAPPING,
    LWLOCK_GROUP_MAX_RESERVED_CSN,
    LWLOCK_GROUP_UPDATE_LOCAL_CSN_MIN,
    LWLOCK_GROUP_CONFLICT_HINT,
    LWLOCK_GROUP_TAC_HEAP,
    LWLOCK_GROUP_UNDO_MAP,
    LWLOCK_GROUP_GET_PAGE_WAL_RECORDS,
    LWLOCK_GROUP_BUF_TRANSFER_PAGE_CACHE,
    LWLOCK_GROUP_BUF_ANTI_CACHE,
    LWLOCK_GROUP_TABLESPACE,
    LWLOCK_GROUP_DATAFILE,
    LWLOCK_GROUP_MAX
};
#pragma GCC visibility pop
}  // namespace DSTORE
#endif  // STORAGE_LWLOCK_DIAGNOSE_H
