/*
 * Copyright (C) 2026 Huawei Technologies Co.,Ltd.
 *
 * dstore is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * dstore is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. if not, see <https://www.gnu.org/licenses/>.
 *
 * ---------------------------------------------------------------------------------
 *
 * posix_signal.h
 *
 * Description:Defines the signal external interfaces wrapper for POSIX standard signal.
 *
 *
 *
 * ---------------------------------------------------------------------------------
 */

#ifndef UTILS_POSIX_SIGNAL_H
#define UTILS_POSIX_SIGNAL_H

#include "defines/common.h"
#include "container/linked_list.h"
#include "defines/utils_errorcode.h"
#include "types/atomic_type.h"
#include "types/data_types.h"
#include "port/port_signal.h"
#include "port/posix_thread.h"
#include "port/posix_mutex.h"
#include "port/posix_pipe.h"

GSDB_BEGIN_C_CODE_DECLS

/*
 * Signal is a type of software interrupt. The signal mechanism is a mode of inter-process communication and
 * adopts the asynchronous communication mode.The Linux system defines 64 types of signals, which are classified
 * into two types: reliable signals and unreliable signals. The first 32 types of signals are unreliable signals
 * and the last 32 types of signals are reliable signals.
 * Unreliable signal: It is also called non-real-time signal. It does not support queuing and may be lost.
 * For example, if the same signal is sent multiple times, the process can receive it only once. The value of the
 * signal ranges from 1 to 31.
 * Reliable signal: It is also called real-time signal. It supports queuing and does not lose signals. It can be
 * received as many times as it is sent. The signal value ranges from 32 to 64.
 * When a non-real-time signal is sent to a process, if the information has been registered in the process, it will
 * not be registered again. As a result, the signal will be lost.When a real-time signal is sent to a process, it is
 * re-registered regardless of whether the signal has been registered in the process. Therefore, the signal is not lost.
 *
 * In Linux, each process has its own signal mask. The signal mask specifies which signals are blocked and which
 * signals are not blocked. Generally, sigmask is invoked to process the signal mask. In addition, each process
 * has its own signal action. This action set specifies how to process signals. Generally, sigaction is invoked
 * to process signals.
 * Threads and signals are processed as follows:
 * 1.If the signal is generated by an abnormality, (such as program errors,SIGPIPE, SIGEGV etc) , only the
 * thread that generates the exception receives and processes the signal.
 * 2.If an internal signal is generated with pthread_kill, only the target thread specified in the pthread_kill
 * parameter is received and processed.
 * 3.If the signal is generated by using the kill command from the outside, usually job control signals such as
 * SIGINT and SIGHUP,the system traverses all threads until a thread that does not block the signal is found,
 * and then invokes it to process the signal. (Generally, it is found from the main thread.) Note that only one
 * thread can receive the signal.
 * 4.Each thread has its own signal mask, but all threads share the signal action of the process. This means that you
 * can call pthread_sigmask (not sigmask) in the thread to determine which signals the thread is blocking. However,you
 * cannot call sigaction to specify how a single thread processes signals. If sigaction is invoked in a thread to
 * process a signal, all threads in the process that do not block the signal will process the signal in the same
 * way when receiving the signal.
 * 5.The mask of the subthread is inherited from the main thread.
 */

/*
 * Based on the signal differences between the Linux and Windows platforms,
 * the signal adaptation policies are as follows:
 * 1.Signals are an asynchronous event communication mechanism between processes or threads,
 * but the event has a higher priority.Signals interrupt the running of the current thread and
 * affect system stability.Therefore, do not use signals.
 * In Linux, all threads block all signals by default. The sigmask is set in the main thread.
 * By using the inheritance relationship of the thread signal mask set,the threads created by
 * the main thread inherit the mask of the main thread.
 * In Windows, the main thread set SIG_IGN for all signals.
 * 2.The signal types and signal processing mechanisms of Linux platform is a superset of the Windows platform.
 * The cross-platform signal adaptation is based on Linux, and some implementations in Windows are empty implementation.
 * 3.Signaling mechanism between threads, implemented through message queues and specialized dispatch thread.
 * Signaling mechanism between processes, implemented through named pipes and specialized dispatch thread.
 */

/*
 * When sending a signal, you can choose to send the additional message content. All signal types use a message queue.
 * When receiving the signal, you can get the specific message according to the specified signal type, or you can
 * get any type.Signal callback functions and signal message processing are separated, so that applications can
 * process them together or separately in different places as required.
 */

/* Signal set wrapper. */
typedef struct SignalSet SignalSet;
struct SignalSet {
    sigset_t signalSet;
};

#define SIGNAL_QUEUE_MAX_MESSAGE_SIZE 128
typedef struct SignalQueues SignalQueues;
struct SignalQueues {
    int portSignalNo;
    size_t actualSize;                           /* Length of the actually sent and received message. */
    char message[SIGNAL_QUEUE_MAX_MESSAGE_SIZE]; /* Message content. The message content is valid only
                                                  * when the value of actualSize is greater than 0. */
};

#define SIGNAL_FILE_PREFIX "gs_utils_signal_"

typedef enum {
    SIGNAL_NO_CALLBACK_TYPE,      /* Signal callback function, which only receives and processes signals. */
    SIGNAL_MESSAGE_CALLBACK_TYPE, /* Signal message callback function, which receives and processes signals and
                                     messages. */
    SIGNAL_CALLBACK_TYPE_END
} SignalCallbackFunctionType;
/* Thread signal context wrapper. */
typedef struct ThreadSignalContext ThreadSignalContext;
struct ThreadSignalContext {
    DListNode threadSignalContextNode; /* Message node. Must be the first member. */
    Mutex mutex;
    Tid tid;
    SignalSet signalSet;
    SignalCallbackFunctionType signalCallbackFunctionType[MAX_SIG_NUM];
    SignalFunction signalFunction[MAX_SIG_NUM];
    SignalMessageFunction signalMessageFunction[MAX_SIG_NUM];
    SignalQueues signalQueues[MAX_SIG_NUM];
};

/* Process signal context wrapper. */
typedef struct ProcessSignalContext ProcessSignalContext;
struct ProcessSignalContext {
    Mutex mutex;    /* Protects the addition and deletion of thread context nodes,
                     * and write and read to pipe when signals are sent between processes. */
    DListHead head; /* The threadSignalContextNode head. */
    Pipe pipe;      /* The pipe used to send signal attached messages between processes. */

    bool signalPipeHandleThreadExit; /* Indicates whether the pipe processing thread exit. */
};
/* Signal initialize. */
UTILS_EXPORT ErrorCode SignalInitialize(void);
/* Destroy signal related resources. */
UTILS_EXPORT void SignalDestroy(void);
/* Clear the signal set. */
UTILS_EXPORT ErrorCode SignalEmptySet(SignalSet *signalSet);
/* Fill all signals into the signal set. */
UTILS_EXPORT ErrorCode SignalFillSet(SignalSet *signalSet);
/* Add a signal to the signal set. */
UTILS_EXPORT ErrorCode SignalAddSet(SignalSet *signalSet, int portSignalNo);
/* Remove a signal from the signal set. */
UTILS_EXPORT ErrorCode SignalDelSet(SignalSet *signalSet, int portSignalNo);
/* Whether a signal is a member of a signal set. */
UTILS_EXPORT ErrorCode SignalIsMember(const SignalSet *signalSet, int portSignalNo);
/* Set signal mask. */
UTILS_EXPORT ErrorCode SignalSetMask(SignalSet *signalSet);
/* Register signal no processing functions for application. */
UTILS_EXPORT SignalFunction Signal(int portSignalNo, SignalFunction handler);
/* Register signal message processing functions for application. */
UTILS_EXPORT SignalMessageFunction SignalMessage(int portSignalNo, SignalMessageFunction handler);
/* Sending a signal to a thread. */
UTILS_EXPORT ErrorCode SendThreadSignal(Tid tid, int portSignalNo, void *signalMessage, size_t messageSize);
/* Sending a signals to a process. */
UTILS_EXPORT ErrorCode SendProcessSignal(Pid pid, int portSignalNo, void *signalMessage, size_t messageSize);
UTILS_EXPORT ErrorCode ProcessKill(Pid pid, int portSignalNo);
UTILS_EXPORT ErrorCode ThreadKill(Tid tid, int portSignalNo);

GSDB_END_C_CODE_DECLS
#endif /* UTILS_POSIX_SIGNAL_H */
