#!/bin/bash
# Copyright (C) 2026 Huawei Technologies Co.,Ltd.
#
# dstore is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# dstore is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. if not, see <https://www.gnu.org/licenses/>.

# pre-commit file
# use clang-format to check style of staged files

readonly CACHED_FILES=$(git diff --cached --name-only |grep '\.[ch]$')

echo -e "\e[93mStart running clang-format\e[0m"
sh utils/tests/scripts/clang_format.sh check files ${CACHED_FILES}

ret=$?
if [ ${ret} -ne 0 ]; then
    echo -e "\e[93mThe issues can be fixed by command:\e[0m"
    echo -e "\e[93m  sh utils/tests/scripts/clang_format.sh fix files \$(git diff --cached --name-only |grep '\.[ch]$')\e[0m"
fi

echo -e "\e[93mFinish running clang-format\e[0m"

exit ${ret}
