/*
 * Copyright (C) 2026 Huawei Technologies Co.,Ltd.
 *
 * dstore is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * dstore is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. if not, see <https://www.gnu.org/licenses/>.
 *
 * ---------------------------------------------------------------------------------------
 *
 * utils_errorcode.h
 *
 * Description: definition of the utils errorCode
 *
 * ---------------------------------------------------------------------------------------
 */

#ifndef UTILS_ERRORCODE_H
#define UTILS_ERRORCODE_H

#include "common.h"
#include "err_code.h"

GSDB_BEGIN_C_CODE_DECLS

/* component ID */
#define UTILS_COMPONENT_ID 0x01

/* module ID */
#define UTILS_EVENT_MODULE_ID           0x01
#define UTILS_COMMON_MODULE_ID          0x02
#define UTILS_THREADPOOL_MODULE_ID      0x03
#define UTILS_TIME_MODULE_ID            0x04
#define UTILS_VFS_MODULE_ID             0x05
#define UTILS_PORT_MODULE_ID            0x06
#define UTILS_THREAD_MESSAGE_MODULE_ID  0x07
#define UTILS_ERRORLOG_MODULE_ID        0x08
#define UTILS_FAULT_INJECTION_MODULE_ID 0x09
#define UTILS_CONFIG_PARSER_MODULE_ID   0x0a
#define UTILS_SECURITY_MODULE_ID        0x0b

// clang-format off
/**************** below common error code ********************************/
#define ERROR_UTILS_COMMON_FAILED   \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_COMMON_MODULE_ID, 0xFFFFFFFF)
#define ERROR_UTILS_COMMON_INVALID_PARAMETER \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_COMMON_MODULE_ID, 0x00000001)
#define ERROR_UTILS_COMMON_EXCEEDED_LIMIT \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_COMMON_MODULE_ID, 0x00000002)
#define ERROR_UTILS_COMMON_NOENOUGH_MEMORY   \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_COMMON_MODULE_ID, 0x00000003)
/* not null violation */
#define ERROR_UTILS_COMMON_NOT_NULL_VIOLATION \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_COMMON_MODULE_ID, 0x00000004)
/* data is corrupted */
#define ERROR_UTILS_COMMON_DATA_CORRUPTED \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_COMMON_MODULE_ID, 0x00000005)
/* integer overflow */
#define ERROR_UTILS_COMMON_INTEGER_OVERFLOW \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_COMMON_MODULE_ID, 0x00000006)
/* division by zero */
#define ERROR_UTILS_COMMON_DIVISION_BY_ZERO \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_COMMON_MODULE_ID, 0x00000007)
/* securec function fail */
#define ERROR_UTILS_COMMON_SECURE_C_FUNCTION_FAILED \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_COMMON_MODULE_ID, 0x00000008)
#define ERROR_UTILS_COMMON_INDEX_OUT_OF_RANGE \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_COMMON_MODULE_ID, 0x00000009)
#define ERROR_UTILS_COMMON_DYNAMIC_ARRAY_IS_EMPTY \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_COMMON_MODULE_ID, 0x0000000A)

/**************** below event error code ********************************/
#define ERROR_UTILS_EVENT_INVALID_ARGS \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_EVENT_MODULE_ID, 0x000000001)
#define ERROR_UTILS_EVENT_VFUNC_NO_IMPL \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_EVENT_MODULE_ID, 0x000000002)
#define ERROR_UTILS_EVENT_OUT_OF_MEMORY \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_EVENT_MODULE_ID, 0x000000003)
#define ERROR_UTILS_EVENT_INVALID_LOOP_STATE \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_EVENT_MODULE_ID, 0x000000004)
#define ERROR_UTILS_EVENT_OVERLIMIT \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_EVENT_MODULE_ID, 0x000000005)
#define ERROR_UTILS_EVENT_CREATE_EPOLL_FAILED \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_EVENT_MODULE_ID, 0x000000006)
#define ERROR_UTILS_EVENT_POLL_CREATE_PIPE_FAILED \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_EVENT_MODULE_ID, 0x000000007)
#define ERROR_UTILS_EVENT_ADD_WAKUPFD_FAILED \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_EVENT_MODULE_ID, 0x000000008)
#define ERROR_UTILS_EVENT_POLL_FDS_REACH_MAX_LIMIT \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_EVENT_MODULE_ID, 0x000000009)
#define ERROR_UTILS_EVENT_POLL_CTL_FAILED \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_EVENT_MODULE_ID, 0x00000000A)
#define ERROR_UTILS_EVENT_POLL_POLLING_FAILED \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_EVENT_MODULE_ID, 0x00000000B)

/**************** below thread pool error code ********************************/
#define UTILS_ERROR_THREADPOOL_NOMEMORY \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_THREADPOOL_MODULE_ID, 0x00000001)
#define UTILS_ERROR_THREADPOOL_NULLPARAMETER \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_THREADPOOL_MODULE_ID, 0x00000002)
#define UTILS_ERROR_THREADPOOL_PARAMETERERROR \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_THREADPOOL_MODULE_ID, 0x00000003)
#define UTILS_ERROR_THREADPOOL_INITFAILED \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_THREADPOOL_MODULE_ID, 0x00000004)
#define UTILS_ERROR_THREADPOOL_ERRSTATE \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_THREADPOOL_MODULE_ID, 0x00000005)
#define UTILS_ERROR_THREADPOOL_ERRTASK \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_THREADPOOL_MODULE_ID, 0x00000006)
#define UTILS_ERROR_THREADPOOL_TOOMANYTASK \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_THREADPOOL_MODULE_ID, 0x00000007)
#define UTILS_ERROR_THREADPOOL_TASKNOTEXIST \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_THREADPOOL_MODULE_ID, 0x00000008)
#define UTILS_ERROR_THREADPOOL_TASKISEXECUTING \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_THREADPOOL_MODULE_ID, 0x00000009)
#define UTILS_ERROR_OPERATION_NOT_SUPPORT \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_THREADPOOL_MODULE_ID, 0x00000010)

/**************** below time error code ********************************/
#define UTILS_ERROR_TIME_UNKNOWN_TIMETYPE \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_TIME_MODULE_ID, 0x00000001)

// clang-format on
GSDB_END_C_CODE_DECLS
#endif /* UTILS_ERRORCODE_H */
