#!/usr/bin/env python
# coding: utf-8
# Copyright (C) 2026 Huawei Technologies Co.,Ltd.
#
# dstore is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# dstore is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. if not, see <https://www.gnu.org/licenses/>.
""" CCT comments generator

Assist to generate the CCT comments for cct_gen_from_template.py
"""

import os
import sys
import logging
import argparse
from itertools import permutations

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)


if __name__ == '__main__':
    aparse = argparse.ArgumentParser(
        prog="cct_auto_comment",
        description="concurrent tests comments CCT:: auto generator"
    )

    aparse.add_argument('--func_num', required=True, help="function number", type=int)
    aparse.add_argument('--timeslot_num', required=True, help="time slot number number", type=int)

    args = aparse.parse_args()

    func_num = args.func_num
    timeslot_num = args.timeslot_num

    combinations = permutations(range(timeslot_num), func_num)

    sections_list = []

    for combination in combinations:
        is_ascending = all(x <= y for x, y in zip(combination, combination[1:]))

        if is_ascending:
            logger.info(combination)

            sections = ["ni"] * timeslot_num
            for _id, val in enumerate(combination):
                fname = "f%d" % (_id + 1)
                sections[val] = fname

            sections_list.append(sections)

            logger.info(sections)

    logger.info("\n------\nplease copy below comments into your template file\n------")

    print("\n/**\n* auto-generated by cct_auto_comment.py with func_num=%d, time_slot=%d ..." 
               % (func_num, timeslot_num))
    for _id, sec in enumerate(sections_list):

        _cct = "* CCT::thread-%d: {" % (_id + 1)
        for _i, s in enumerate(sec):
            _cct += "t%d:%s" % (_i + 1, s)
            if _i < len(sec) - 1:
                _cct.append(", ")
        _cct.append("}")

        print(_cct)
    print("*/")
