/*
 * Copyright (C) 2026 Huawei Technologies Co.,Ltd.
 *
 * dstore is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * dstore is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. if not, see <https://www.gnu.org/licenses/>.
 */
#include <gtest/gtest.h>
#include "heap/dstore_heap_update.h"
#include "transaction/dstore_transaction_mgr.h"
#include "ut_heap/ut_heap_multi_thread.h"
#include "errorcode/dstore_heap_error_code.h"
#include "lock/dstore_table_lock_mgr.h"

/**
* auto-generated by cct_auto_comment.py with func_num=2, time_slot=3 ...
* CCT::thread-1: {t1:f1, t2:f2, t3:ni}
* CCT::thread-2: {t1:f1, t2:ni, t3:f2}
* CCT::thread-3: {t1:ni, t2:f1, t3:f2}
*/
TEST_F(UTHeapMultiThread, HeapMultiThreadConcurrentUpdateDeleteTest1_level0)
{

    const int TUPLE_LEN = 3000;
    m_counter = 0;

    // CCT::b_f1
    HeapInsertFixedLengthTuple(TUPLE_LEN);    
    // CCT::e_f1

    // CCT::b_f2
    HeapUpdateConcurrently(TUPLE_LEN);
    // CCT::e_f2

    HeapDeleteConcurrently();


    EXPECT_EQ(m_counter.load(), 1);
}