/*
 * Copyright (C) 2026 Huawei Technologies Co.,Ltd.
 *
 * dstore is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * dstore is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. if not, see <https://www.gnu.org/licenses/>.
 */
#include <gtest/gtest.h>
#include "heap/dstore_heap_update.h"
#include "transaction/dstore_transaction_mgr.h"
#include "ut_heap/ut_heap_multi_thread.h"
#include "errorcode/dstore_heap_error_code.h"
#include "lock/dstore_table_lock_mgr.h"

/**
* auto-generated by cct_auto_comment.py with func_num=5, time_slot=7 ...
* CCT::thread-1: {t1:f1, t2:f2, t3:f3, t4:f4, t5:f5, t6:ni, t7:ni}
* CCT::thread-2: {t1:f1, t2:f2, t3:f3, t4:f4, t5:ni, t6:f5, t7:ni}
* CCT::thread-3: {t1:f1, t2:f2, t3:f3, t4:f4, t5:ni, t6:ni, t7:f5}
* CCT::thread-4: {t1:f1, t2:f2, t3:f3, t4:ni, t5:f4, t6:f5, t7:ni}
* CCT::thread-5: {t1:f1, t2:f2, t3:f3, t4:ni, t5:f4, t6:ni, t7:f5}
* CCT::thread-6: {t1:f1, t2:f2, t3:f3, t4:ni, t5:ni, t6:f4, t7:f5}
* CCT::thread-7: {t1:f1, t2:f2, t3:ni, t4:f3, t5:f4, t6:f5, t7:ni}
* CCT::thread-8: {t1:f1, t2:f2, t3:ni, t4:f3, t5:f4, t6:ni, t7:f5}
* CCT::thread-9: {t1:f1, t2:f2, t3:ni, t4:f3, t5:ni, t6:f4, t7:f5}
* CCT::thread-10: {t1:f1, t2:f2, t3:ni, t4:ni, t5:f3, t6:f4, t7:f5}
* CCT::thread-11: {t1:f1, t2:ni, t3:f2, t4:f3, t5:f4, t6:f5, t7:ni}
* CCT::thread-12: {t1:f1, t2:ni, t3:f2, t4:f3, t5:f4, t6:ni, t7:f5}
* CCT::thread-13: {t1:f1, t2:ni, t3:f2, t4:f3, t5:ni, t6:f4, t7:f5}
* CCT::thread-14: {t1:f1, t2:ni, t3:f2, t4:ni, t5:f3, t6:f4, t7:f5}
* CCT::thread-15: {t1:f1, t2:ni, t3:ni, t4:f2, t5:f3, t6:f4, t7:f5}
* CCT::thread-16: {t1:ni, t2:f1, t3:f2, t4:f3, t5:f4, t6:f5, t7:ni}
* CCT::thread-17: {t1:ni, t2:f1, t3:f2, t4:f3, t5:f4, t6:ni, t7:f5}
* CCT::thread-18: {t1:ni, t2:f1, t3:f2, t4:f3, t5:ni, t6:f4, t7:f5}
* CCT::thread-19: {t1:ni, t2:f1, t3:f2, t4:ni, t5:f3, t6:f4, t7:f5}
* CCT::thread-20: {t1:ni, t2:f1, t3:ni, t4:f2, t5:f3, t6:f4, t7:f5}
* CCT::thread-21: {t1:ni, t2:ni, t3:f1, t4:f2, t5:f3, t6:f4, t7:f5}
*/
TEST_F(UTHeapMultiThread, HeapMultiThreadConcurrentUpdateDeleteTest2_level0)
{

    const int TUPLE_LEN = 3000;
    m_counter = 0;

    // CCT::b_f1
    HeapInsertFixedLengthTuple(TUPLE_LEN);    
    // CCT::e_f1

    // CCT::b_f2
    HeapUpdateConcurrently(TUPLE_LEN);
    // CCT::e_f2

    EXPECT_TRUE(m_counter.load() == 1);

    HeapFetchAndCheckWithSnapshot();

    // CCT::b_f3
    HeapInsertFixedLengthTupleWithFixedTabSmgr(TUPLE_LEN*3);
    // CCT::e_f3

    // CCT::b_f4
    HeapUpdateConcurrently(TUPLE_LEN*3);
    // CCT::e_f4

    // CCT::b_f5
    HeapDeleteConcurrently();
    // CCT::e_f5 

    ASSERT_GE(m_counter.load(), 1);
}