/*
 * Copyright (C) 2026 Huawei Technologies Co.,Ltd.
 *
 * dstore is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * dstore is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. if not, see <https://www.gnu.org/licenses/>.
 *
 * ---------------------------------------------------------------------------------
 *
 * vfs_error_code.h
 *
 * Description:
 * This file defines vfs error code
 * vfs error code low 32-bit range division
 * Range [0, 0x1000): VFS module error code and local disk error code
 * Range [0x1000, 0x2000): VFS module and PageStore common error code
 * Range [0x2000, 0x3000): VFS resource error code
 * Range [0x3000, 0x4000): StoreSpace resource error code
 * Range [0x4000, 0x5000): File resource error code
 * Attention:
 * Range >= 0x00010000 is reserved for PageStore internal error code
 *
 * ---------------------------------------------------------------------------------
 */

#ifndef UTILS_VFS_ERROR_CODE_H
#define UTILS_VFS_ERROR_CODE_H

#include "defines/utils_errorcode.h"

// clang-format off

/* VFS and PageStore low-32 bit error code definition */
/* Range [0x1000, 0x2000): VFS module and PageStore common error code */
#define VFS_ERROR_UNKNOWN_ERROR_LOW_32                   0x1000
#define VFS_ERROR_INVALID_ARGUMENT_LOW_32                0x1001
#define VFS_ERROR_RESOURCE_IS_EXIST_LOW_32               0x1002
#define VFS_ERROR_RESOURCE_NOT_EXIST_LOW_32              0x1003
#define VFS_ERROR_RESOURCE_NOT_ENOUGH_LOW_32             0x1004
#define VFS_ERROR_RESOURCE_NOT_RELEASE_LOW_32            0x1005
#define VFS_ERROR_NEED_RETRY_AGAIN_LOW_32                0x1006
#define VFS_ERROR_COMMUNICATION_FAILED_LOW_32            0x1007
#define VFS_ERROR_OPERATION_NOT_SUPPORT_LOW_32           0x1008
#define VFS_ERROR_AIO_CONTEXT_INITL_FAIL_LOW_32          0x1009
#define VFS_ERROR_AIO_WRITE_SUBMIT_FAIL_LOW_32           0x1010
#define VFS_ERROR_AIO_READ_SUBMIT_FAIL_LOW_32            0x1011
#define VFS_ERROR_AIO_GET_EVENTS_FAIL_LOW_32             0x1012
#define VFS_ERROR_IO_FENCING_REFUSE_LOW_32               0x1013
#define VFS_ERROR_REQUEST_OVERLOAD_LOW_32                0x1014
#define VFS_ERROR_PAGESTORE_INNER_ERROR_LOW_32           0x1015
#define VFS_ERROR_PAGESTORE_POOL_SPACE_NOT_ENOUGH_LOW_32 0x1016
#define VFS_ERROR_SAL_IS_STOPPED_LOW_32                  0x1017
/* Range [0x2000, 0x3000): VFS resource error code */
#define VFS_ERROR_VFS_IS_EXIST_LOW_32                    0x2000
#define VFS_ERROR_VFS_NOT_EXIST_LOW_32                   0x2001
#define VFS_ERROR_VFS_IN_USE_LOW_32                      0x2002
/* Range [0x3000, 0x4000): StoreSpace resource error code */
#define VFS_ERROR_STORESPACE_IS_EXIST_LOW_32             0x3000
#define VFS_ERROR_STORESPACE_NOT_EXIST_LOW_32            0x3001
#define VFS_ERROR_STORESPACE_IN_USE_LOW_32               0x3002
#define VFS_ERROR_STORESPACE_SPACE_NOT_ENOUGH_LOW_32     0x3003
#define VFS_ERROR_STORESPACE_UPDATE_BELOW_LIMIT_LOW_32   0x3004
/* Range [0x4000, 0x5000): File resource error code */
#define VFS_ERROR_FILE_IS_EXIST_LOW_32                   0x4000
#define VFS_ERROR_FILE_NOT_EXIST_LOW_32                  0x4001
#define VFS_ERROR_FILE_NOT_CLOSE_LOW_32                  0x4002
#define VFS_ERROR_FILE_READ_PADDING_BUFFER_LOW_32        0x4003
#define VFS_ERROR_FILE_PADDING_NOT_CONTINUE_LOW_32       0x4004
#define VFS_ERROR_FILE_PADDING_CONFLICT_LOW_32           0x4005
#define VFS_ERROR_FILE_ALREADY_OPEN_LOW_32               0x4006
#define VFS_ERROR_FILE_WRITE_SEAL_LOW_32                 0x4007
#define VFS_ERROR_FILE_LOCK_INVALID_LOW_32               0x4008
#define VFS_ERROR_FILE_WRITE_CONFLICT_LOW_32             0x4009
/* Range [0x5000, 0x6000): Snapshot resource error code */
#define VFS_ERROR_SNAPSHOT_IS_EXIST_LOW_32              0x5000
#define VFS_ERROR_SNAPSHOT_NOT_EXIST_LOW_32             0x5001
#define VFS_ERROR_FILE_SNAPSHOT_NOT_EXIST_LOW_32        0x5002
#define VFS_ERROR_SNAPSHOT_REACH_LIMIT_LOW_32           0x5003
/* Range [0x6000, 0x7000): Tenant resource error code */
#define VFS_ERROR_TENANT_NOT_EXIST_LOW_32               0x6000
#define VFS_ERROR_TENANT_IS_EXIST_LOW_32                0x6001
#define VFS_ERROR_TENANT_IN_USE_LOW_32                  0x6002

/* VFS and PageStore 64 bit error code definition */
#define VFS_ERROR_UNKNOWN_ERROR \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_UNKNOWN_ERROR_LOW_32)
#define VFS_ERROR_INVALID_ARGUMENT \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_INVALID_ARGUMENT_LOW_32)
#define VFS_ERROR_RESOURCE_IS_EXIST \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_RESOURCE_IS_EXIST_LOW_32)
#define VFS_ERROR_RESOURCE_NOT_EXIST \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_RESOURCE_NOT_EXIST_LOW_32)
#define VFS_ERROR_RESOURCE_NOT_ENOUGH \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_RESOURCE_NOT_ENOUGH_LOW_32)
#define VFS_ERROR_RESOURCE_NOT_RELEASE  \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_RESOURCE_NOT_RELEASE_LOW_32)
#define VFS_ERROR_NEED_RETRY_AGAIN \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_NEED_RETRY_AGAIN_LOW_32)
#define VFS_ERROR_COMMUNICATION_FAILED \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_COMMUNICATION_FAILED_LOW_32)
#define VFS_ERROR_OPERATION_NOT_SUPPORT \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_OPERATION_NOT_SUPPORT_LOW_32)
#define VFS_ERROR_AIO_CONTEXT_INITL_FAIL \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_AIO_CONTEXT_INITL_FAIL_LOW_32)
#define VFS_ERROR_AIO_WRITE_SUBMIT_FAIL \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_AIO_WRITE_SUBMIT_FAIL_LOW_32)
#define VFS_ERROR_AIO_READ_SUBMIT_FAIL \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_AIO_READ_SUBMIT_FAIL_LOW_32)
#define VFS_ERROR_AIO_GET_EVENTS_FAIL \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_AIO_GET_EVENTS_FAIL_LOW_32)
#define VFS_ERROR_IO_FENCING_REFUSE \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_IO_FENCING_REFUSE_LOW_32)
#define VFS_ERROR_REQUEST_OVERLOAD \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_REQUEST_OVERLOAD_LOW_32)
#define VFS_ERROR_PAGESTORE_INNER_ERROR \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_PAGESTORE_INNER_ERROR_LOW_32)
#define VFS_ERROR_PAGESTORE_POOL_SPACE_NOT_ENOUGH \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_PAGESTORE_POOL_SPACE_NOT_ENOUGH_LOW_32)
#define VFS_ERROR_SAL_IS_STOPPED \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_SAL_IS_STOPPED_LOW_32)
#define VFS_ERROR_VFS_IS_EXIST \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_VFS_IS_EXIST_LOW_32)
#define VFS_ERROR_VFS_NOT_EXIST \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_VFS_NOT_EXIST_LOW_32)
#define VFS_ERROR_VFS_IN_USE \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_VFS_IN_USE_LOW_32)
#define VFS_ERROR_STORESPACE_IS_EXIST \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_STORESPACE_IS_EXIST_LOW_32)
#define VFS_ERROR_STORESPACE_NOT_EXIST \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_STORESPACE_NOT_EXIST_LOW_32)
#define VFS_ERROR_STORESPACE_IN_USE \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_STORESPACE_IN_USE_LOW_32)
#define VFS_ERROR_STORESPACE_SPACE_NOT_ENOUGH \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_STORESPACE_SPACE_NOT_ENOUGH_LOW_32)
#define VFS_ERROR_STORESPACE_UPDATE_BELOW_LIMIT \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_STORESPACE_UPDATE_BELOW_LIMIT_LOW_32)
#define VFS_ERROR_FILE_IS_EXIST \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_FILE_IS_EXIST_LOW_32)
#define VFS_ERROR_FILE_NOT_EXIST \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_FILE_NOT_EXIST_LOW_32)
#define VFS_ERROR_FILE_NOT_CLOSE \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_FILE_NOT_CLOSE_LOW_32)
#define VFS_ERROR_FILE_READ_PADDING_BUFFER \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_FILE_READ_PADDING_BUFFER_LOW_32)
#define VFS_ERROR_FILE_PADDING_NOT_CONTINUE \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_FILE_PADDING_NOT_CONTINUE_LOW_32)
#define VFS_ERROR_FILE_PADDING_CONFLICT \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_FILE_PADDING_CONFLICT_LOW_32)
#define VFS_ERROR_FILE_ALREADY_OPEN \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_FILE_ALREADY_OPEN_LOW_32)
#define VFS_ERROR_FILE_WRITE_SEAL \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_FILE_WRITE_SEAL_LOW_32)
#define VFS_ERROR_FILE_LOCK_INVALID \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_FILE_LOCK_INVALID_LOW_32)
#define VFS_ERROR_FILE_WRITE_CONFLICT \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_FILE_WRITE_CONFLICT_LOW_32)
#define VFS_ERROR_SNAPSHOT_IS_EXIST \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_SNAPSHOT_IS_EXIST_LOW_32)
#define VFS_ERROR_SNAPSHOT_NOT_EXIST \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_SNAPSHOT_NOT_EXIST_LOW_32)
#define VFS_ERROR_FILE_SNAPSHOT_NOT_EXIST \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_FILE_SNAPSHOT_NOT_EXIST_LOW_32)
#define VFS_ERROR_SNAPSHOT_REACH_LIMIT \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_SNAPSHOT_REACH_LIMIT_LOW_32)
#define VFS_ERROR_TENANT_NOT_EXIST \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_TENANT_NOT_EXIST_LOW_32)
#define VFS_ERROR_TENANT_IS_EXIST \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_TENANT_IS_EXIST_LOW_32)
#define VFS_ERROR_TENANT_IN_USE \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, VFS_ERROR_TENANT_IN_USE_LOW_32)
/* we should define error messages in vfs_error_code.c when add error code */

/* vfs error code */
#define VFS_ERROR_LOCAL_ADAPTER_NOT_INIT \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, 0x00000001)
#define VFS_ERROR_LOCAL_ADAPTER_ALREADY_INIT \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, 0x00000002)
#define VFS_ERROR_PARAMETERS_INVALID \
    VFS_ERROR_INVALID_ARGUMENT
#define VFS_ERROR_LOCAL_FILE_OPERATION_FAILED \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, 0x00000004)
#define VFS_ERROR_OUT_OF_MEMORY \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, 0x00000005)
#define VFS_ERROR_CREATE_FILE_EXIST \
    VFS_ERROR_FILE_IS_EXIST
#define VFS_ERROR_OPEN_FILE_NOT_EXIST \
    VFS_ERROR_FILE_NOT_EXIST
#define VFS_ERROR_VFS_MODULE_ALREADY_INIT \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, 0x00000008)
#define VFS_ERROR_VFS_MODULE_NOT_INIT \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, 0x00000009)
#define VFS_ERROR_DISK_HAS_NO_SPACE \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, 0x0000000A)
#define VFS_ERROR_OPENED_FILE_REACH_MAX \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, 0x0000000B)
#define VFS_ERROR_LOAD_ADAPTER_LIB_FAIL \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, 0x0000000C)
#define VFS_ERROR_LOAD_ADAPTER_FUNC_FAIL \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, 0x0000000D)
#define VFS_ERROR_OFFLOAD_ADAPTER_LIB_FAIL \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, 0x0000000E)
#define VFS_ERROR_FILE_ACCESS_DENIED \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, 0x0000000F)
#define VFS_ERROR_UNMOUNT_STATIC_VFS_FAIL \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, 0x00000010)
#define VFS_ERROR_MEM_ALLOCATOR_IS_SET \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, 0x00000011)
#define VFS_ERROR_SECURE_FUNCTION_FAIL \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, 0x00000012)
#define VFS_ERROR_OPERATION_DENIED \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, 0x00000013)
#define VFS_ERROR_CREATE_VFS_NAME_EXIST \
    VFS_ERROR_VFS_IS_EXIST
#define VFS_ERROR_VFS_NAME_NOT_EXIST \
    VFS_ERROR_VFS_NOT_EXIST
#define VFS_ERROR_VFS_RESOURCE_NOT_RELEASE \
    VFS_ERROR_RESOURCE_NOT_RELEASE
#define VFS_ERROR_REOPEN_FILE_FAIL \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, 0x00000017)
#define VFS_ERROR_REMOVE_FILE_NOT_EXIST \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, 0x00000018)
#define VFS_ERROR_LOCK_FILE_FAIL \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, 0x00000019)
#define VFS_ERROR_UNLOCK_FILE_FAIL \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, 0x0000001A)
#define VFS_ERROR_IO_FENCING_REFUSE_BY_OWNER \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, 0x0000001B)
#define VFS_ERROR_VFS_ERROR_IO_FENCE_TERMID_LOWER \
    MAKE_ERROR_CODE(UTILS_COMPONENT_ID, UTILS_VFS_MODULE_ID, 0x0000001C)
/* we should define error messages in vfs_error_code.c when add error code */
// clang-format off

#endif /* UTILS_VFS_ERROR_CODE_H */
